import { getCompleteCuisineCatalog } from "@/lib/cuisineCatalogs/completeCatalogs";

export interface CuisineDishCatalog {
  iconicDishes: string[];
  pantryAnchors: string[];
}

export const CUISINE_DISH_CATALOGS: Record<string, CuisineDishCatalog> = {
  egyptian: {
    iconicDishes: [
      "ful medames",
      "taameya",
      "koshary",
      "molokhia",
      "feteer meshaltet",
      "hawawshi",
      "macarona bechamel",
      "kofta",
      "kebab halla",
      "fattah",
      "mahshi kromb",
      "waraq enab",
      "kousa mahshi",
      "mahshi filfil",
      "bamia",
      "fasolia beida",
      "bessara",
      "eggah",
      "shakshuka",
      "sayadeya",
      "roz meammar",
      "hamam mahshi",
      "alexandrian liver",
      "kebda eskandarani",
      "egyptian liver sandwiches",
      "sujuk",
      "shawarma arabi",
      "lentil soup",
      "lesan asfour soup",
      "moussaka",
      "torly",
      "okra stew",
      "rabbit molokhia",
      "bat bel roz",
      "duck with freekeh",
      "kaware",
      "foul bil tahina",
      "foul iskandarani",
      "taagen bamia",
      "taagen kofta",
      "taagen chicken and onions",
      "farakh meshwi",
      "egyptian grilled chicken",
      "chicken molokhia",
      "chicken fattah",
      "chicken negresco",
      "samak singari",
      "egyptian fish tagine",
      "alexandrian shrimp",
      "seafood sayadeya",
      "roz bel khalta",
      "basbousa",
      "kunafa",
      "om ali",
      "roz bel laban",
      "mahalabia",
      "qatayef",
      "zalabya",
      "meshabek",
      "goulash",
      "sabanegh"
    ],
    pantryAnchors: [
      "fava bean",
      "lentil",
      "rice",
      "pasta",
      "tomato",
      "egg",
      "ground meat",
      "beef",
      "liver",
      "chicken",
      "fish",
      "shrimp",
      "seafood",
      "baladi bread"
    ]
  },
  turkish: {
    iconicDishes: [
      "mercimek corbasi",
      "ezogelin corbasi",
      "menemen",
      "cilbir",
      "sucuklu yumurta",
      "pogaca",
      "simit",
      "gozleme",
      "ispanakli pide",
      "kiymali pide",
      "lahmacun",
      "manti",
      "cig kofte",
      "icli kofte",
      "adana kebab",
      "urfa kebab",
      "izgara kofte",
      "tavuk sis",
      "testi kebabi",
      "iskender kebab",
      "beyti kebab",
      "doner kebab",
      "arnavut cigeri",
      "edirne tava cigeri",
      "turkish liver saute",
      "etli ekmek",
      "kumpir",
      "hamsili pilav",
      "karniyarik",
      "patlican kebabi",
      "imam bayildi",
      "sarma",
      "dolma",
      "kurufasulye",
      "pilav",
      "yayla corbasi",
      "kisir",
      "sigara boregi",
      "su boregi",
      "mucver",
      "kunefe",
      "baklava",
      "sutlac"
    ],
    pantryAnchors: [
      "egg",
      "tomato",
      "pepper",
      "yogurt",
      "eggplant",
      "ground meat",
      "liver",
      "chicken",
      "fish",
      "shrimp",
      "bulgur",
      "flatbread"
    ]
  },
  italian: {
    iconicDishes: [
      "spaghetti carbonara",
      "cacio e pepe",
      "amatriciana",
      "pasta alla norma",
      "pasta e fagioli",
      "minestrone",
      "ribollita",
      "pappa al pomodoro",
      "risotto alla milanese",
      "mushroom risotto",
      "arancini",
      "lasagna alla bolognese",
      "cannelloni",
      "gnocchi al pesto",
      "gnocchi alla sorrentina",
      "ravioli ricotta e spinach",
      "tagliatelle al ragu",
      "osso buco",
      "saltimbocca",
      "pollo cacciatore",
      "chicken piccata",
      "parmigiana di melanzane",
      "polenta e funghi",
      "focaccia",
      "pizza margherita",
      "pizza marinara",
      "calzone",
      "caprese salad",
      "bruschetta",
      "panzanella",
      "vitello tonnato",
      "bistecca alla fiorentina",
      "cotoletta alla milanese",
      "porchetta",
      "involtini",
      "seafood risotto",
      "spaghetti alle vongole",
      "linguine al pesto",
      "frittata",
      "farinata",
      "suppli",
      "tiramisu",
      "cannoli",
      "panna cotta",
      "gelato",
      "gnudi",
      "orecchiette con cime di rapa",
      "pasta al pomodoro",
      "puttanesca",
      "aglio e olio"
    ],
    pantryAnchors: [
      "pasta",
      "tomato",
      "olive oil",
      "garlic",
      "parmesan",
      "mozzarella",
      "basil",
      "rice",
      "ground meat",
      "chicken",
      "fish",
      "shrimp"
    ]
  },
  middleeastern: {
    iconicDishes: [
      "hummus",
      "baba ghanoush",
      "mutabbal",
      "tabbouleh",
      "fattoush",
      "falafel",
      "ful medames",
      "labneh",
      "manakish",
      "kibbeh",
      "kibbeh nayyeh",
      "shawarma",
      "chicken shawarma wrap",
      "beef shawarma plate",
      "lamb shawarma bowl",
      "beef and lamb shawarma",
      "shish tawook",
      "kofta kebab",
      "kebab karaz",
      "mujaddara",
      "maqluba",
      "mansaf",
      "musakhan",
      "qidreh",
      "dolma",
      "kousa mahshi",
      "waraq enab",
      "fasoulia",
      "bamia",
      "molokhia",
      "lentil soup",
      "fatteh",
      "fatayer",
      "cheese sambousek",
      "lahmacun",
      "pide",
      "gozleme",
      "manti",
      "iskender kebab",
      "adana kebab",
      "ghormeh sabzi",
      "khoresh bademjan",
      "fesenjan",
      "tahdig",
      "kuku sabzi",
      "ash reshteh",
      "shakshuka",
      "kanafeh",
      "basbousa",
      "baklava",
      "qatayef",
      "makdous",
      "quzi",
      "harees"
    ],
    pantryAnchors: [
      "chickpea",
      "lentil",
      "tahini",
      "yogurt",
      "rice",
      "bulgur",
      "eggplant",
      "parsley",
      "ground meat",
      "beef",
      "lamb",
      "chicken",
      "fish",
      "shrimp",
      "seafood"
    ]
  },
  mediterranean: {
    iconicDishes: [
      "greek salad",
      "horiatiki",
      "briam",
      "tourlou",
      "fasolakia ladera",
      "revithada",
      "spanakorizo",
      "prasorizo",
      "fava santorini",
      "hummus with mushrooms",
      "roasted cauliflower with tahini",
      "eggplant chickpea stew",
      "caponata",
      "pasta alla norma dairy free",
      "vegan gemista",
      "vegetarian dolma",
      "vegetarian stuffed zucchini",
      "vegan lentil moussaka",
      "white bean tomato stew",
      "artichoke potato stew",
      "chickpea vegetable tagine",
      "grilled sea bass",
      "baked white fish",
      "ratatouille",
      "salade nicoise",
      "paella",
      "fideua",
      "gazpacho",
      "tortilla espanola",
      "escalivada",
      "caprese salad",
      "bruschetta",
      "pasta puttanesca",
      "pesto pasta",
      "ciambotta",
      "pappa al pomodoro",
      "ribollita",
      "fasolada",
      "gigantes plaki",
      "spanakopita",
      "tiropita",
      "moussaka",
      "souvlaki",
      "chicken souvlaki",
      "grilled lamb chops",
      "stuffed peppers",
      "stuffed grape leaves",
      "couscous with vegetables",
      "shakshuka",
      "chermoula fish",
      "roasted eggplant with yogurt",
      "tabbouleh",
      "hummus bowl",
      "falafel plate",
      "lentil salad",
      "chickpea salad",
      "white bean stew",
      "grilled chicken with lemon and herbs",
      "baked orzo",
      "shrimp saganaki",
      "seafood stew",
      "grilled octopus",
      "tuna salad with olives",
      "roasted vegetable medley",
      "patatas bravas",
      "gemista",
      "imam bayildi",
      "avgolemono soup",
      "sardines with lemon"
    ],
    pantryAnchors: [
      "olive oil",
      "tomato",
      "lemon",
      "chickpea",
      "lentil",
      "fish",
      "yogurt",
      "eggplant",
      "ground meat",
      "chicken",
      "shrimp",
      "seafood"
    ]
  },
  indian: {
    iconicDishes: [
      "dal tadka",
      "dal makhani",
      "chana masala",
      "rajma",
      "palak paneer",
      "paneer butter masala",
      "matar paneer",
      "saag paneer",
      "aloo gobi",
      "aloo matar",
      "baingan bharta",
      "bhindi masala",
      "veg pulao",
      "biryani",
      "chicken biryani",
      "butter chicken",
      "chicken tikka masala",
      "rogan josh",
      "vindaloo",
      "keema matar",
      "egg bhurji",
      "masala omelette",
      "poha",
      "upma",
      "idli sambar",
      "masala dosa",
      "uttapam",
      "chole bhature",
      "pav bhaji",
      "vada pav",
      "samosa",
      "pakora",
      "paratha",
      "aloo paratha",
      "khichdi",
      "sambar rice",
      "curd rice",
      "lemon rice",
      "tamarind rice",
      "fish curry",
      "korma",
      "kadhai chicken",
      "tandoori chicken",
      "kadai paneer",
      "malai kofta",
      "dal baati",
      "litti chokha",
      "appam stew",
      "kathi roll",
      "dosa"
    ],
    pantryAnchors: [
      "lentil",
      "chickpea",
      "kidney bean",
      "rice",
      "onion",
      "tomato",
      "ginger",
      "garlic",
      "ground meat",
      "chicken",
      "fish",
      "shrimp"
    ]
  },
  mexican: {
    iconicDishes: [
      "tacos al pastor",
      "carnitas",
      "birria",
      "barbacoa",
      "cochinita pibil",
      "tinga de pollo",
      "chilaquiles",
      "huevos rancheros",
      "huevos a la mexicana",
      "enchiladas verdes",
      "enchiladas rojas",
      "enchiladas suizas",
      "enfrijoladas",
      "entomatadas",
      "quesadillas",
      "sopes",
      "gorditas",
      "huaraches",
      "molletes",
      "tamales",
      "pozole rojo",
      "pozole verde",
      "menudo",
      "caldo tlalpeno",
      "sopa de tortilla",
      "sopa de fideo",
      "arroz rojo",
      "arroz con pollo",
      "chile relleno",
      "chiles en nogada",
      "mole poblano",
      "mole negro",
      "pipian verde",
      "pipian rojo",
      "tlayudas",
      "cemita",
      "pambazo",
      "torta ahogada",
      "aguachile",
      "pescado a la veracruzana",
      "ceviche",
      "carne asada",
      "alambre",
      "flautas",
      "taquitos dorados",
      "papadzules",
      "salbutes",
      "panuchos",
      "frijoles charros",
      "esquites"
    ],
    pantryAnchors: [
      "corn tortilla",
      "bean",
      "tomato",
      "onion",
      "chili",
      "cilantro",
      "lime",
      "rice",
      "ground meat",
      "chicken",
      "fish",
      "shrimp"
    ]
  },
  american: {
    iconicDishes: [
      "cheeseburger",
      "barbecue ribs",
      "smoked brisket",
      "fried chicken",
      "mac and cheese",
      "meatloaf",
      "pot roast",
      "roast turkey",
      "chicken pot pie",
      "clam chowder",
      "gumbo",
      "jambalaya",
      "shrimp and grits",
      "chicken and waffles",
      "pancakes",
      "waffles",
      "eggs benedict",
      "biscuits and gravy",
      "breakfast hash",
      "grilled cheese",
      "blt",
      "club sandwich",
      "sloppy joe",
      "philly cheesesteak",
      "reuben",
      "po boy",
      "lobster roll",
      "chili",
      "cornbread",
      "hush puppies",
      "baked beans",
      "collard greens",
      "fried green tomatoes",
      "mashed potatoes and gravy",
      "pulled pork sandwich",
      "buffalo wings",
      "cobb salad",
      "chef salad",
      "texas chili",
      "new york strip steak",
      "hot dog",
      "breakfast burrito",
      "banana bread",
      "apple pie",
      "pecan pie",
      "key lime pie",
      "brownies",
      "red velvet cake",
      "chocolate chip cookies",
      "s'mores"
    ],
    pantryAnchors: [
      "egg",
      "potato",
      "bread",
      "cheddar",
      "ground beef",
      "ground meat",
      "chicken",
      "fish",
      "shrimp",
      "cornmeal",
      "barbecue sauce"
    ]
  },
  asian: {
    iconicDishes: [
      "fried rice",
      "chicken fried rice",
      "vegetable stir fry",
      "beef and broccoli",
      "chow mein",
      "lo mein",
      "mapo tofu",
      "kung pao chicken",
      "hot and sour soup",
      "wonton soup",
      "congee",
      "teriyaki chicken",
      "yakisoba",
      "ramen",
      "udon stir fry",
      "katsu curry",
      "sushi bowl",
      "onigiri",
      "bibimbap",
      "japchae",
      "bulgogi",
      "kimchi fried rice",
      "tofu stir fry",
      "pad thai",
      "pad see ew",
      "basil chicken",
      "red curry",
      "green curry",
      "pho",
      "bun cha",
      "banh xeo",
      "spring rolls",
      "summer rolls",
      "nasi goreng",
      "mee goreng",
      "hainanese chicken rice",
      "laksa",
      "satay",
      "beef rendang",
      "chicken adobo",
      "sinigang",
      "arroz caldo",
      "char kway teow",
      "dumplings",
      "gyoza",
      "bao buns",
      "orange chicken",
      "sesame noodles",
      "miso soup",
      "egg drop soup"
    ],
    pantryAnchors: [
      "rice",
      "noodle",
      "soy sauce",
      "ginger",
      "garlic",
      "sesame",
      "tofu",
      "scallion",
      "ground meat",
      "chicken",
      "fish",
      "shrimp"
    ]
  },
  thai: {
    iconicDishes: [
      "pad thai",
      "pad see ew",
      "pad kee mao",
      "pad krapow",
      "khao pad",
      "green curry",
      "red curry",
      "massaman curry",
      "panang curry",
      "yellow curry",
      "tom yum goong",
      "tom kha gai",
      "larb",
      "som tam",
      "khao soi",
      "pad woon sen",
      "rad na",
      "kai jeow",
      "gaeng jued",
      "satay gai",
      "moo ping",
      "gai yang",
      "nam tok",
      "kua kling",
      "crying tiger",
      "khao man gai",
      "jok",
      "khao tom",
      "yum woon sen",
      "pla rad prik",
      "pla neung manao",
      "goong ob woon sen",
      "pad prik khing",
      "gaeng som",
      "gaeng pa",
      "gaeng keow wan",
      "gaeng massaman nua",
      "gaeng phet ped yang",
      "khao mok gai",
      "khanom jeen nam ya",
      "khanom jeen green curry",
      "pad pak ruam",
      "stir-fried morning glory",
      "pad krapow tofu",
      "tom saap",
      "pineapple fried rice",
      "basil seafood",
      "larb gai",
      "yum nua",
      "mango sticky rice"
    ],
    pantryAnchors: [
      "fish sauce",
      "rice",
      "rice noodle",
      "basil",
      "lime",
      "chili",
      "coconut milk",
      "garlic",
      "ground meat",
      "chicken",
      "fish",
      "shrimp"
    ]
  }
};

export function getCuisineDishCatalog(cuisine: string) {
  const detailedCatalog = buildDetailedCuisineDishCatalog(cuisine);
  return detailedCatalog ?? CUISINE_DISH_CATALOGS[normalizeCuisineCatalogKey(cuisine)];
}

export function getCuisineDishReferenceText(cuisine: string, limit = 50) {
  const catalog = getCuisineDishCatalog(cuisine);
  if (!catalog) return "";
  return catalog.iconicDishes.slice(0, limit).join(", ");
}

export function getCuisinePantryAnchors(cuisine: string) {
  return getCuisineDishCatalog(cuisine)?.pantryAnchors ?? [];
}

function normalizeCuisineCatalogKey(value: string) {
  return value.toLowerCase().replace(/[^a-z]/g, "");
}

function buildDetailedCuisineDishCatalog(cuisine: string): CuisineDishCatalog | null {
  const catalog = getCompleteCuisineCatalog(cuisine);
  if (!catalog?.length) return null;

  return {
    iconicDishes: [...catalog]
      .sort((left, right) => right.iconicScore - left.iconicScore || left.names.english[0].localeCompare(right.names.english[0]))
      .flatMap((dish) => dish.names.english)
      .map(normalizeDishName)
      .filter(Boolean),
    pantryAnchors: Array.from(
      new Set(
        catalog
          .flatMap((dish) => [...dish.primaryIngredients, ...dish.optionalIngredients])
          .map(normalizeDishName)
          .filter(Boolean)
      )
    )
  };
}

function normalizeDishName(value: string) {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}
