export enum RecipeGenerationStatus {
  SUCCESS_AI = "SUCCESS_AI",
  SUCCESS_DATASET = "SUCCESS_DATASET",
  SUCCESS_CACHE = "SUCCESS_CACHE",
  PARTIAL_RESULTS = "PARTIAL_RESULTS",
  NO_RESULTS = "NO_RESULTS"
}
