import type { CuisineDish, CuisineKey, MealType, SubCuisineKey } from "./types";

type DishInput = {
  cuisine: CuisineKey;
  description: string;
  english: string[];
  id: string;
  iconicScore: number;
  mealTypes: MealType[];
  native?: string[];
  optionalIngredients: string[];
  primaryIngredients: string[];
  region: string;
  subCuisine?: SubCuisineKey;
};

function dish(input: DishInput): CuisineDish {
  return {
    cuisine: input.cuisine,
    description: input.description,
    iconicScore: input.iconicScore,
    id: input.id,
    mealTypes: input.mealTypes,
    names: {
      english: input.english,
      native: input.native ?? input.english
    },
    optionalIngredients: input.optionalIngredients,
    primaryIngredients: input.primaryIngredients,
    region: input.region,
    subCuisine: input.subCuisine
  };
}

export const INDIAN_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "dal-tadka", english: ["Dal Tadka"], native: ["Dal Tadka"], region: "North India", description: "Yellow lentils tempered with ghee, cumin, garlic, and chilies", primaryIngredients: ["lentils", "ghee", "cumin"], optionalIngredients: ["garlic", "chili", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 92 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "chana-masala", english: ["Chana Masala"], native: ["Chana Masala"], region: "North India", description: "Chickpeas simmered with onion, tomato, ginger, and garam masala", primaryIngredients: ["chickpeas", "tomato", "onion"], optionalIngredients: ["ginger", "garam masala", "cilantro"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "baingan-bharta", english: ["Baingan Bharta"], native: ["Baingan Bharta"], region: "North India", description: "Smoky roasted eggplant mashed with tomato, onion, ginger, and spices", primaryIngredients: ["eggplant", "tomato", "onion"], optionalIngredients: ["ginger", "garlic", "cilantro"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "vegetable-korma", english: ["Vegetable Korma"], native: ["Vegetable Korma"], region: "South India", description: "Mixed vegetables simmered in coconut or nut-based curry sauce", primaryIngredients: ["mixed vegetables", "coconut milk", "spices"], optionalIngredients: ["cashew", "ginger", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "chickpea-coconut-curry", english: ["Chickpea Coconut Curry"], native: ["Chana Coconut Curry"], region: "South India", description: "Chickpeas simmered with coconut milk, curry leaves, mustard seed, and tomato", primaryIngredients: ["chickpeas", "coconut milk", "tomato"], optionalIngredients: ["mustard seed", "curry leaves", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 87 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "vegetable-biryani", english: ["Vegetable Biryani"], native: ["Vegetable Biryani"], region: "India", description: "Layered spiced rice with vegetables, herbs, saffron, and fried onions", primaryIngredients: ["rice", "mixed vegetables", "spices"], optionalIngredients: ["mint", "saffron", "fried onion"], mealTypes: ["lunch", "dinner"], iconicScore: 89 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "rajma", english: ["Rajma"], native: ["Rajma"], region: "Punjab", description: "Kidney bean curry served with rice", primaryIngredients: ["kidney beans", "tomato", "onion"], optionalIngredients: ["ginger", "garlic", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "aloo-gobi", english: ["Aloo Gobi"], native: ["Aloo Gobi"], region: "North India", description: "Dry cauliflower and potato sabzi with turmeric and cumin", primaryIngredients: ["potato", "cauliflower", "turmeric"], optionalIngredients: ["cumin", "ginger", "cilantro"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "palak-paneer", english: ["Palak Paneer"], native: ["Palak Paneer"], region: "North India", description: "Paneer cubes in spiced spinach gravy", primaryIngredients: ["spinach", "paneer", "cream"], optionalIngredients: ["garlic", "ginger", "garam masala"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "vegan-palak-tofu", english: ["Vegan Palak Paneer With Tofu", "Palak Tofu"], native: ["Palak Tofu"], region: "North India", description: "Tofu cubes simmered in spiced spinach gravy using coconut milk or cashew cream instead of dairy paneer or cream", primaryIngredients: ["tofu", "spinach", "tomato"], optionalIngredients: ["coconut milk", "cashew", "garam masala"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "paneer-butter-masala", english: ["Paneer Butter Masala"], native: ["Paneer Butter Masala"], region: "North India", description: "Paneer in buttery tomato-cashew gravy", primaryIngredients: ["paneer", "tomato", "butter"], optionalIngredients: ["cream", "cashew", "fenugreek"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "butter-chicken", english: ["Butter Chicken", "Murgh Makhani"], native: ["Murgh Makhani"], region: "Delhi", description: "Tandoori chicken simmered in buttery tomato gravy", primaryIngredients: ["chicken", "tomato", "butter"], optionalIngredients: ["cream", "fenugreek", "garam masala"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "chicken-tikka-masala", english: ["Chicken Tikka Masala"], native: ["Chicken Tikka Masala"], region: "North Indian diaspora", description: "Chicken tikka in spiced tomato cream sauce", primaryIngredients: ["chicken", "tomato", "cream"], optionalIngredients: ["yogurt", "garam masala", "ginger"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "vegan-tikka-masala", english: ["Vegan Tikka Masala", "Tofu Tikka Masala", "Vegetable Tikka Masala"], native: ["Vegan Tikka Masala"], region: "North Indian diaspora", description: "Tofu or roasted vegetables in a rich spiced tomato masala sauce with coconut milk or cashew cream instead of dairy", primaryIngredients: ["tofu", "tomato", "spices"], optionalIngredients: ["coconut milk", "cauliflower", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "masala-dosa", english: ["Masala Dosa"], native: ["Masala Dosa"], region: "South India", description: "Crisp rice-lentil crepe filled with spiced potatoes", primaryIngredients: ["rice batter", "lentils", "potato"], optionalIngredients: ["mustard seed", "curry leaves", "chutney"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "idli-sambar", english: ["Idli Sambar"], native: ["Idli Sambar"], region: "South India", description: "Steamed rice-lentil cakes served with lentil vegetable stew", primaryIngredients: ["rice batter", "lentils", "sambar"], optionalIngredients: ["coconut chutney", "curry leaves"], mealTypes: ["breakfast", "lunch"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "vada-sambar", english: ["Vada Sambar"], native: ["Vada Sambar"], region: "South India", description: "Fried lentil doughnuts served with sambar", primaryIngredients: ["urad dal", "sambar", "curry leaves"], optionalIngredients: ["coconut chutney", "chili"], mealTypes: ["breakfast", "snack"], iconicScore: 86 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "uttapam", english: ["Uttapam"], native: ["Uttapam"], region: "South India", description: "Thick rice-lentil pancake with onion, chili, and tomato", primaryIngredients: ["rice batter", "onion", "tomato"], optionalIngredients: ["chili", "coconut chutney"], mealTypes: ["breakfast", "lunch"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "avial", english: ["Avial"], native: ["Avial"], region: "Kerala", description: "Mixed vegetables in coconut-yogurt sauce", primaryIngredients: ["mixed vegetables", "coconut", "yogurt"], optionalIngredients: ["curry leaves", "cumin", "green chili"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "kerala-fish-curry", english: ["Kerala Fish Curry"], native: ["Meen Curry"], region: "Kerala", description: "Fish simmered with coconut, chili, curry leaves, and tamarind", primaryIngredients: ["fish", "coconut milk", "tamarind"], optionalIngredients: ["curry leaves", "chili", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "hyderabadi-biryani", english: ["Hyderabadi Biryani"], native: ["Hyderabadi Biryani"], region: "Hyderabad", description: "Layered rice and marinated meat cooked with saffron and spices", primaryIngredients: ["rice", "chicken", "yogurt"], optionalIngredients: ["saffron", "mint", "fried onion"], mealTypes: ["lunch", "dinner"], iconicScore: 95 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "lamb-rogan-josh", english: ["Rogan Josh"], native: ["Rogan Josh"], region: "Kashmir", description: "Aromatic lamb curry with Kashmiri chili and warm spices", primaryIngredients: ["lamb", "yogurt", "kashmiri chili"], optionalIngredients: ["ginger", "fennel", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "pakistani-beef-kofta-curry", english: ["Pakistani Beef Kofta Curry", "Beef Kofta Curry"], native: ["Beef Kofta Curry"], region: "Pakistan", description: "Ground beef meatballs simmered in spiced tomato-onion curry with cilantro, ginger, garlic, and rice or flatbread when listed", primaryIngredients: ["ground beef", "tomato", "spices"], optionalIngredients: ["onion", "ginger", "garlic", "cilantro", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "pav-bhaji", english: ["Pav Bhaji"], native: ["Pav Bhaji"], region: "Mumbai", description: "Mashed spiced vegetable curry served with buttered bread rolls", primaryIngredients: ["potato", "mixed vegetables", "bread"], optionalIngredients: ["butter", "onion", "cilantro"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "vada-pav", english: ["Vada Pav"], native: ["Vada Pav"], region: "Mumbai", description: "Spiced potato fritter in a bread roll with chutneys", primaryIngredients: ["potato", "bread", "chutney"], optionalIngredients: ["chili", "garlic", "gram flour"], mealTypes: ["snack", "street_food"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "poha", english: ["Poha"], native: ["Poha"], region: "Maharashtra", description: "Flattened rice cooked with mustard seed, onion, turmeric, and peanuts", primaryIngredients: ["flattened rice", "onion", "turmeric"], optionalIngredients: ["peanuts", "curry leaves", "lemon"], mealTypes: ["breakfast", "snack"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "dhokla", english: ["Dhokla"], native: ["Dhokla"], region: "Gujarat", description: "Steamed fermented gram flour cakes with mustard tempering", primaryIngredients: ["gram flour", "yogurt", "mustard seed"], optionalIngredients: ["curry leaves", "green chili"], mealTypes: ["breakfast", "snack"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "eastIndian", id: "macher-jhol", english: ["Macher Jhol"], native: ["Macher Jhol"], region: "Bengal", description: "Light Bengali fish curry with potato, tomato, and mustard oil", primaryIngredients: ["fish", "potato", "mustard oil"], optionalIngredients: ["tomato", "turmeric", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "indian", subCuisine: "eastIndian", id: "litti-chokha", english: ["Litti Chokha"], native: ["Litti Chokha"], region: "Bihar", description: "Roasted wheat balls filled with sattu served with mashed vegetables", primaryIngredients: ["wheat flour", "sattu", "eggplant"], optionalIngredients: ["potato", "tomato", "mustard oil"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 82 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "samosa", english: ["Samosa"], native: ["Samosa"], region: "India", description: "Fried pastry filled with spiced potatoes and peas", primaryIngredients: ["flour", "potato", "peas"], optionalIngredients: ["cumin", "chutney", "chili"], mealTypes: ["snack", "street_food"], iconicScore: 92 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "kheer", english: ["Kheer"], native: ["Kheer"], region: "India", description: "Rice pudding with milk, sugar, cardamom, and nuts", primaryIngredients: ["rice", "milk", "sugar"], optionalIngredients: ["cardamom", "nuts", "saffron"], mealTypes: ["dessert"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "gulab-jamun", english: ["Gulab Jamun"], native: ["Gulab Jamun"], region: "North India", description: "Milk-solid dumplings soaked in cardamom syrup", primaryIngredients: ["milk solids", "flour", "syrup"], optionalIngredients: ["cardamom", "rose water"], mealTypes: ["dessert"], iconicScore: 90 })
];

export const THAI_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pad-thai", english: ["Pad Thai"], native: ["Pad Thai"], region: "Central Thailand", description: "Stir-fried rice noodles with tamarind, egg, tofu or shrimp, and peanuts", primaryIngredients: ["rice noodles", "tamarind", "egg"], optionalIngredients: ["shrimp", "tofu", "peanuts"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 96 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "tom-yum-goong", english: ["Tom Yum Goong"], native: ["Tom Yum Goong"], region: "Central Thailand", description: "Hot-sour shrimp soup with lemongrass, galangal, and lime leaf", primaryIngredients: ["shrimp", "lemongrass", "lime"], optionalIngredients: ["galangal", "kaffir lime leaf", "chili"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 94 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "green-curry-chicken", english: ["Thai Green Curry Chicken", "Gaeng Keow Wan Gai"], native: ["Gaeng Keow Wan Gai"], region: "Central Thailand", description: "Chicken simmered in green curry paste and coconut milk", primaryIngredients: ["chicken", "green curry paste", "coconut milk"], optionalIngredients: ["eggplant", "basil", "fish sauce"], mealTypes: ["lunch", "dinner"], iconicScore: 92 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "red-curry", english: ["Thai Red Curry"], native: ["Gaeng Phed"], region: "Central Thailand", description: "Red curry paste simmered with coconut milk and meat or vegetables", primaryIngredients: ["red curry paste", "coconut milk", "meat"], optionalIngredients: ["bamboo shoots", "basil", "fish sauce"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "vegetarian-green-curry", english: ["Vegetarian Thai Green Curry"], native: ["Gaeng Keow Wan Pak"], region: "Central Thailand", description: "Green curry with coconut milk, Thai eggplant, vegetables, basil, and tofu when appropriate", primaryIngredients: ["green curry paste", "coconut milk", "vegetables"], optionalIngredients: ["tofu", "thai basil", "eggplant"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pad-krapow-tofu", english: ["Pad Krapow Tofu", "Thai Basil Tofu"], native: ["Pad Krapow Tofu"], region: "Central Thailand", description: "Tofu stir-fried with holy basil, garlic, chili, and soy-style seasoning for plant-based plans", primaryIngredients: ["tofu", "holy basil", "chili"], optionalIngredients: ["garlic", "rice", "green beans"], mealTypes: ["lunch", "dinner"], iconicScore: 89 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "thai-colorful-vegetable-stir-fry", english: ["Thai Colorful Vegetable Stir Fry", "Thai Mixed Vegetable Stir Fry"], native: ["Pad Pak Ruam"], region: "Thailand", description: "Bright stir-fry of broccoli, snap peas, bell pepper, carrot, mushrooms, and tofu with garlic, ginger, basil, and soy-style seasoning", primaryIngredients: ["mixed vegetables", "broccoli", "mushrooms"], optionalIngredients: ["tofu", "basil", "ginger", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "tom-yum-mushroom", english: ["Tom Yum Mushroom"], native: ["Tom Yum Hed"], region: "Central Thailand", description: "Hot-sour mushroom soup with lemongrass, lime, galangal, chili, and herbs", primaryIngredients: ["mushrooms", "lemongrass", "lime"], optionalIngredients: ["galangal", "kaffir lime leaf", "chili"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 88 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pineapple-fried-rice", english: ["Thai Pineapple Fried Rice"], native: ["Khao Pad Sapparot"], region: "Thailand", description: "Thai fried rice with pineapple, vegetables, cashews, curry powder, and shrimp or tofu", primaryIngredients: ["rice", "pineapple", "vegetables"], optionalIngredients: ["cashew", "shrimp", "tofu"], mealTypes: ["lunch", "dinner"], iconicScore: 87 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "massaman-curry", english: ["Massaman Curry"], native: ["Gaeng Massaman"], region: "Central Thailand", description: "Mild Muslim-influenced curry with potato, peanuts, and warm spices", primaryIngredients: ["beef", "potato", "coconut milk"], optionalIngredients: ["peanuts", "tamarind", "cinnamon"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "panang-curry", english: ["Panang Curry"], native: ["Panang Curry"], region: "Central Thailand", description: "Thick coconut curry with red curry paste and kaffir lime leaf", primaryIngredients: ["meat", "panang curry paste", "coconut milk"], optionalIngredients: ["peanuts", "lime leaf", "basil"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "thai", subCuisine: "northeasternThai", id: "som-tam", english: ["Som Tam", "Green Papaya Salad"], native: ["Som Tam"], region: "Isan", description: "Pounded green papaya salad with lime, chili, fish sauce, and peanuts", primaryIngredients: ["green papaya", "lime", "chili"], optionalIngredients: ["fish sauce", "peanuts", "tomato"], mealTypes: ["lunch", "side", "street_food"], iconicScore: 94 }),
  dish({ cuisine: "thai", subCuisine: "northeasternThai", id: "larb-gai", english: ["Larb Gai"], native: ["Larb Gai"], region: "Isan", description: "Minced chicken salad with toasted rice powder, lime, chili, and herbs", primaryIngredients: ["ground chicken", "lime", "toasted rice"], optionalIngredients: ["mint", "fish sauce", "chili"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "northeasternThai", id: "nam-tok", english: ["Nam Tok"], native: ["Nam Tok"], region: "Isan", description: "Grilled meat salad with lime, chili, herbs, and toasted rice powder", primaryIngredients: ["grilled beef", "lime", "toasted rice"], optionalIngredients: ["mint", "fish sauce", "chili"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pad-krapow-gai", english: ["Pad Krapow Gai", "Thai Basil Chicken"], native: ["Pad Krapow Gai"], region: "Central Thailand", description: "Stir-fried minced chicken with holy basil and chilies", primaryIngredients: ["ground chicken", "holy basil", "chili"], optionalIngredients: ["garlic", "fish sauce", "egg"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 92 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "khao-pad", english: ["Khao Pad", "Thai Fried Rice"], native: ["Khao Pad"], region: "Thailand", description: "Thai fried rice with egg, onion, and a protein", primaryIngredients: ["rice", "egg", "onion"], optionalIngredients: ["shrimp", "chicken", "lime"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pad-see-ew", english: ["Pad See Ew"], native: ["Pad See Ew"], region: "Central Thailand", description: "Wide rice noodles stir-fried with dark soy sauce, egg, and Chinese broccoli", primaryIngredients: ["wide rice noodles", "egg", "soy sauce"], optionalIngredients: ["chinese broccoli", "chicken", "beef"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "rad-na", english: ["Rad Na"], native: ["Rad Na"], region: "Central Thailand", description: "Wide noodles topped with savory gravy and Chinese broccoli", primaryIngredients: ["wide rice noodles", "gravy", "chinese broccoli"], optionalIngredients: ["pork", "chicken", "soy sauce"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "northernThai", id: "khao-soi", english: ["Khao Soi"], native: ["Khao Soi"], region: "Northern Thailand", description: "Coconut curry noodle soup with chicken and crispy noodles", primaryIngredients: ["egg noodles", "chicken", "coconut milk"], optionalIngredients: ["curry paste", "pickled mustard greens", "lime"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 92 }),
  dish({ cuisine: "thai", subCuisine: "southernThai", id: "gaeng-som", english: ["Gaeng Som"], native: ["Gaeng Som"], region: "Southern Thailand", description: "Sour orange curry with fish or shrimp and vegetables", primaryIngredients: ["fish", "tamarind", "curry paste"], optionalIngredients: ["vegetables", "shrimp", "lime"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "tom-kha-gai", english: ["Tom Kha Gai"], native: ["Tom Kha Gai"], region: "Central Thailand", description: "Coconut chicken soup with galangal, lemongrass, and lime", primaryIngredients: ["chicken", "coconut milk", "galangal"], optionalIngredients: ["lemongrass", "lime", "mushroom"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "satay-gai", english: ["Chicken Satay", "Satay Gai"], native: ["Satay Gai"], region: "Thailand", description: "Grilled marinated chicken skewers with peanut sauce", primaryIngredients: ["chicken", "peanut sauce", "turmeric"], optionalIngredients: ["coconut milk", "cucumber relish"], mealTypes: ["snack", "street_food", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "tod-man-pla", english: ["Tod Man Pla", "Thai Fish Cakes"], native: ["Tod Man Pla"], region: "Thailand", description: "Fried fish cakes with red curry paste and lime leaf", primaryIngredients: ["fish", "red curry paste", "lime leaf"], optionalIngredients: ["green beans", "cucumber relish"], mealTypes: ["snack", "side"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "yam-woon-sen", english: ["Yam Woon Sen", "Glass Noodle Salad"], native: ["Yam Woon Sen"], region: "Thailand", description: "Spicy glass noodle salad with lime, chili, herbs, and seafood or pork", primaryIngredients: ["glass noodles", "lime", "chili"], optionalIngredients: ["shrimp", "ground pork", "cilantro"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "mango-sticky-rice", english: ["Mango Sticky Rice"], native: ["Khao Niao Mamuang"], region: "Thailand", description: "Sweet coconut sticky rice served with ripe mango", primaryIngredients: ["sticky rice", "mango", "coconut milk"], optionalIngredients: ["sugar", "sesame"], mealTypes: ["dessert"], iconicScore: 94 })
];

export const MEDITERRANEAN_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "greek-salad", english: ["Greek Salad", "Horiatiki"], native: ["Horiatiki"], region: "Greece", description: "Tomato, cucumber, onion, olives, and feta with olive oil", primaryIngredients: ["tomato", "cucumber", "feta"], optionalIngredients: ["olive", "onion", "oregano"], mealTypes: ["lunch", "side"], iconicScore: 92 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "moussaka", english: ["Moussaka"], native: ["Moussaka"], region: "Greece", description: "Layered eggplant, spiced meat sauce, and bechamel", primaryIngredients: ["eggplant", "ground meat", "bechamel"], optionalIngredients: ["potato", "tomato", "cinnamon"], mealTypes: ["lunch", "dinner"], iconicScore: 92 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "spanakopita", english: ["Spanakopita"], native: ["Spanakopita"], region: "Greece", description: "Spinach and feta pie baked in phyllo", primaryIngredients: ["phyllo", "spinach", "feta"], optionalIngredients: ["dill", "egg", "onion"], mealTypes: ["breakfast", "lunch", "snack"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "souvlaki", english: ["Souvlaki"], native: ["Souvlaki"], region: "Greece", description: "Grilled marinated meat skewers often served with pita and tzatziki", primaryIngredients: ["meat", "pita", "tzatziki"], optionalIngredients: ["lemon", "oregano", "tomato"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 90 }),
  dish({ cuisine: "mediterranean", id: "slow-grilled-rack-lamb-mustard-herbs", english: ["Slow-Grilled Rack of Lamb with Mustard and Herbs", "Rack of Lamb with Mustard and Herbs"], native: ["Rack of Lamb with Mustard and Herbs"], region: "Mediterranean", description: "Slow-grilled rack of lamb or lamb chops with mustard, rosemary, herbs, olive oil, and a light greens salad", primaryIngredients: ["rack of lamb", "mustard", "herbs"], optionalIngredients: ["rosemary", "olive oil", "arugula", "radish"], mealTypes: ["lunch", "dinner"], iconicScore: 87 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "tzatziki", english: ["Tzatziki"], native: ["Tzatziki"], region: "Greece", description: "Yogurt cucumber dip with garlic, dill, and olive oil", primaryIngredients: ["yogurt", "cucumber", "garlic"], optionalIngredients: ["dill", "olive oil", "lemon"], mealTypes: ["side", "snack"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "dolmades", english: ["Dolmades"], native: ["Dolmades"], region: "Greece", description: "Grape leaves stuffed with rice, herbs, and sometimes meat", primaryIngredients: ["grape leaves", "rice", "herbs"], optionalIngredients: ["ground meat", "lemon", "olive oil"], mealTypes: ["lunch", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "paella-valenciana", english: ["Paella Valenciana"], native: ["Paella Valenciana"], region: "Valencia", description: "Saffron rice cooked with chicken, rabbit, beans, and vegetables", primaryIngredients: ["rice", "saffron", "chicken"], optionalIngredients: ["rabbit", "green beans", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "seafood-paella-bell-peppers", english: ["Seafood Paella with Bell Peppers", "Seafood Paella"], native: ["Paella de Marisco"], region: "Spain", description: "Saffron rice cooked in a wide pan with shrimp, mussels or clams, bell peppers, tomato, peas, and lemon", primaryIngredients: ["rice", "shrimp", "bell pepper"], optionalIngredients: ["mussels", "clams", "saffron", "lemon"], mealTypes: ["lunch", "dinner"], iconicScore: 91 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "gazpacho", english: ["Gazpacho"], native: ["Gazpacho"], region: "Andalusia", description: "Cold blended tomato soup with cucumber, pepper, and olive oil", primaryIngredients: ["tomato", "cucumber", "olive oil"], optionalIngredients: ["pepper", "bread", "garlic"], mealTypes: ["lunch", "soup"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "tortilla-espanola", english: ["Tortilla Espanola", "Spanish Tortilla"], native: ["Tortilla Espanola"], region: "Spain", description: "Thick omelet with potatoes and onions", primaryIngredients: ["egg", "potato", "onion"], optionalIngredients: ["olive oil", "salt"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "pan-con-tomate", english: ["Pan Con Tomate"], native: ["Pan Con Tomate"], region: "Catalonia", description: "Toasted bread rubbed with tomato, garlic, and olive oil", primaryIngredients: ["bread", "tomato", "olive oil"], optionalIngredients: ["garlic", "salt"], mealTypes: ["breakfast", "snack", "side"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "patatas-bravas", english: ["Patatas Bravas"], native: ["Patatas Bravas"], region: "Spain", description: "Fried potatoes served with spicy bravas sauce", primaryIngredients: ["potato", "tomato sauce", "paprika"], optionalIngredients: ["garlic aioli", "olive oil"], mealTypes: ["side", "snack"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "fattoush-mediterranean", english: ["Fattoush"], native: ["Fattoush"], region: "Levant", description: "Chopped salad with toasted pita, sumac, and lemon dressing", primaryIngredients: ["pita", "tomato", "cucumber"], optionalIngredients: ["sumac", "lettuce", "mint"], mealTypes: ["lunch", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "hummus-mediterranean", english: ["Hummus"], native: ["Hummus"], region: "Eastern Mediterranean", description: "Chickpea tahini dip with lemon and olive oil", primaryIngredients: ["chickpeas", "tahini", "lemon"], optionalIngredients: ["olive oil", "garlic", "paprika"], mealTypes: ["breakfast", "snack", "side"], iconicScore: 92 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "avocado-chickpea-salad-cups", english: ["Avocado and Chickpea Salad Cups", "Chickpea Lettuce Cups"], native: ["Avocado Chickpea Salad Cups"], region: "Eastern Mediterranean", description: "Fresh lettuce cups filled with chickpeas, avocado, cucumber, tomato, herbs, lemon, and olive oil", primaryIngredients: ["chickpeas", "avocado", "lettuce"], optionalIngredients: ["cucumber", "tomato", "parsley", "lemon"], mealTypes: ["breakfast", "lunch", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "greek-salad-jar", english: ["Greek Salad Upgrade in a Jar", "Greek Salad Jar"], native: ["Greek Salad Jar"], region: "Greece", description: "Layered Greek-style salad with cucumber, tomato, red onion, chickpeas or quinoa, herbs, lemon, and olive oil for meal prep", primaryIngredients: ["cucumber", "tomato", "chickpeas"], optionalIngredients: ["quinoa", "red onion", "olive oil", "lemon"], mealTypes: ["breakfast", "lunch", "side"], iconicScore: 85 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "mediterranean-lentil-salad", english: ["Mediterranean Lentil Salad", "Herbed Lentil Salad"], native: ["Mediterranean Lentil Salad"], region: "Eastern Mediterranean", description: "Brown or green lentils tossed with cucumber, tomato, herbs, lemon, olive oil, and tahini when desired", primaryIngredients: ["lentils", "cucumber", "tomato"], optionalIngredients: ["parsley", "mint", "tahini", "lemon"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", id: "roasted-veggie-chickpea-bowl", english: ["Roasted Veggie and Chickpea Bowl", "Roasted Vegetable Chickpea Bowl"], native: ["Roasted Veggie Chickpea Bowl"], region: "Mediterranean", description: "Roasted broccoli, cauliflower, peppers, carrots, squash, onion, and chickpeas served as a colorful vegetable bowl with tahini or lemon dressing", primaryIngredients: ["chickpeas", "roasted vegetables", "tahini"], optionalIngredients: ["broccoli", "cauliflower", "pepper", "carrot"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", id: "cucumber-tomato-avocado-salad", english: ["Cucumber Tomato Avocado Salad"], native: ["Cucumber Tomato Avocado Salad"], region: "Mediterranean", description: "Cucumber, tomato, avocado, herbs, lemon, and olive oil in a bright vegetable salad", primaryIngredients: ["cucumber", "tomato", "avocado"], optionalIngredients: ["parsley", "mint", "lemon", "olive oil"], mealTypes: ["breakfast", "lunch", "side"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "yiayia-creamy-pasta", english: ["Yiayia's Creamy Pasta", "Greek Creamy Pasta"], native: ["Yiayia's Creamy Pasta"], region: "Greece", description: "Short pasta in a comforting tomato-orange creamy sauce using plant milk or olive-oil tomato sauce for dairy-free plans", primaryIngredients: ["pasta", "tomato", "plant milk"], optionalIngredients: ["basil", "garlic", "nutritional yeast"], mealTypes: ["lunch", "dinner"], iconicScore: 82 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "briam", english: ["Briam"], native: ["Briam"], region: "Greece", description: "Greek roasted vegetable tray with potatoes, zucchini, eggplant, tomato, herbs, and olive oil", primaryIngredients: ["potato", "zucchini", "eggplant"], optionalIngredients: ["tomato", "olive oil", "oregano"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "fasolakia-ladera", english: ["Fasolakia Ladera", "Greek Green Beans"], native: ["Fasolakia"], region: "Greece", description: "Green beans stewed in tomato, olive oil, onion, garlic, and herbs", primaryIngredients: ["green beans", "tomato", "olive oil"], optionalIngredients: ["potato", "onion", "dill"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "spicy-fasolada", english: ["Creamy Spicy Fasolada", "White Bean Soup"], native: ["Fasolada"], region: "Greece", description: "Greek white bean soup with tomato, carrot, celery, herbs, olive oil, and a creamy texture without dairy when needed", primaryIngredients: ["white beans", "tomato", "carrot"], optionalIngredients: ["celery", "olive oil", "chili", "herbs"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 87 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "creamy-greek-potato-salad", english: ["Creamy Greek Potato Salad", "Greek Potato Salad"], native: ["Greek Potato Salad"], region: "Greece", description: "Potato salad with red onion, herbs, lemon, olives, and yogurt or plant-based creamy dressing depending on diet", primaryIngredients: ["potato", "red onion", "herbs"], optionalIngredients: ["plant yogurt", "olive", "lemon", "dill"], mealTypes: ["lunch", "side"], iconicScore: 82 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "gemista-vegan", english: ["Vegan Gemista", "Greek Stuffed Tomatoes and Peppers"], native: ["Gemista"], region: "Greece", description: "Tomatoes and peppers stuffed with rice, herbs, vegetables, and olive oil", primaryIngredients: ["tomato", "pepper", "rice"], optionalIngredients: ["herbs", "zucchini", "olive oil"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "mediterranean", id: "imam-bayildi", english: ["Imam Bayildi"], native: ["Imam Bayildi"], region: "Eastern Mediterranean", description: "Eggplant stuffed with tomato, onion, garlic, herbs, and olive oil", primaryIngredients: ["eggplant", "tomato", "onion"], optionalIngredients: ["garlic", "olive oil", "parsley"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "shakshuka-mediterranean", english: ["Shakshuka"], native: ["Shakshuka"], region: "Mediterranean", description: "Eggs poached in tomato and pepper sauce", primaryIngredients: ["egg", "tomato", "pepper"], optionalIngredients: ["onion", "garlic", "cumin"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", id: "ratatouille", english: ["Ratatouille"], native: ["Ratatouille"], region: "Provence", description: "Vegetable stew of eggplant, zucchini, pepper, and tomato", primaryIngredients: ["eggplant", "zucchini", "tomato"], optionalIngredients: ["pepper", "olive oil", "herbs"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", id: "crispy-zucchini-rolls", english: ["Crispy Zucchini Rolls", "Crispy Zucchini Herb Rolls"], native: ["Crispy Zucchini Rolls"], region: "Mediterranean", description: "Thin zucchini strips rolled around herbs and a dairy-free tofu or vegetable filling, then baked or pan-seared until golden", primaryIngredients: ["zucchini", "herbs", "tofu"], optionalIngredients: ["lemon", "garlic", "nutritional yeast"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 82 }),
  dish({ cuisine: "mediterranean", id: "nicoise-salad", english: ["Nicoise Salad"], native: ["Salade Nicoise"], region: "Nice", description: "Tuna, egg, olives, green beans, tomato, and potatoes", primaryIngredients: ["tuna", "egg", "green beans"], optionalIngredients: ["olive", "potato", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", id: "bouillabaisse", english: ["Bouillabaisse"], native: ["Bouillabaisse"], region: "Marseille", description: "Mediterranean fish stew with saffron, fennel, and rouille", primaryIngredients: ["fish", "saffron", "fennel"], optionalIngredients: ["shellfish", "tomato", "bread"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", id: "caponata", english: ["Caponata"], native: ["Caponata"], region: "Sicily", description: "Sweet-sour eggplant relish with celery, capers, and tomato", primaryIngredients: ["eggplant", "tomato", "capers"], optionalIngredients: ["celery", "olive", "vinegar"], mealTypes: ["side", "lunch"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", id: "baked-feta", english: ["Baked Feta"], native: ["Baked Feta"], region: "Eastern Mediterranean", description: "Feta baked with tomatoes, olive oil, and herbs", primaryIngredients: ["feta", "tomato", "olive oil"], optionalIngredients: ["oregano", "pepper", "bread"], mealTypes: ["lunch", "side"], iconicScore: 80 }),
  dish({ cuisine: "mediterranean", id: "seafood-orzo", english: ["Seafood Orzo"], native: ["Seafood Orzo"], region: "Mediterranean coast", description: "Orzo cooked with seafood, tomato, herbs, and olive oil", primaryIngredients: ["orzo", "seafood", "tomato"], optionalIngredients: ["olive oil", "parsley", "lemon"], mealTypes: ["lunch", "dinner"], iconicScore: 80 })
];

export const AMERICAN_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "american", id: "hamburger", english: ["Hamburger"], native: ["Hamburger"], region: "United States", description: "Ground beef patty served in a bun with classic toppings", primaryIngredients: ["ground beef", "bun", "lettuce"], optionalIngredients: ["cheese", "tomato", "pickle"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "american", id: "cheeseburger", english: ["Cheeseburger"], native: ["Cheeseburger"], region: "United States", description: "Burger with melted cheese and classic condiments", primaryIngredients: ["ground beef", "bun", "cheese"], optionalIngredients: ["pickle", "onion", "ketchup"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "american", subCuisine: "southernAmerican", id: "fried-chicken", english: ["Fried Chicken"], native: ["Fried Chicken"], region: "American South", description: "Seasoned chicken pieces dredged and fried crisp", primaryIngredients: ["chicken", "flour", "buttermilk"], optionalIngredients: ["paprika", "hot sauce", "oil"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "american", subCuisine: "southernAmerican", id: "biscuits-and-gravy", english: ["Biscuits and Gravy"], native: ["Biscuits and Gravy"], region: "American South", description: "Buttermilk biscuits topped with sausage gravy", primaryIngredients: ["biscuits", "sausage", "milk"], optionalIngredients: ["flour", "black pepper"], mealTypes: ["breakfast"], iconicScore: 88 }),
  dish({ cuisine: "american", subCuisine: "southernAmerican", id: "shrimp-and-grits", english: ["Shrimp and Grits"], native: ["Shrimp and Grits"], region: "Lowcountry", description: "Shrimp served over creamy corn grits with pepper-onion sauce; use dairy-free grits when needed", primaryIngredients: ["shrimp", "grits", "pepper"], optionalIngredients: ["scallion", "cheese", "plant milk"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", subCuisine: "cajunCreole", id: "gumbo", english: ["Gumbo"], native: ["Gumbo"], region: "Louisiana", description: "Okra or roux-thickened stew with seafood, chicken, or sausage", primaryIngredients: ["roux", "okra", "sausage"], optionalIngredients: ["shrimp", "chicken", "rice"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 92 }),
  dish({ cuisine: "american", subCuisine: "cajunCreole", id: "jambalaya", english: ["Jambalaya"], native: ["Jambalaya"], region: "Louisiana", description: "One-pot rice dish with sausage, chicken, seafood, and Cajun seasoning", primaryIngredients: ["rice", "sausage", "chicken"], optionalIngredients: ["shrimp", "pepper", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "american", subCuisine: "newEngland", id: "clam-chowder", english: ["New England Clam Chowder"], native: ["Clam Chowder"], region: "New England", description: "Creamy clam soup with potatoes and onions", primaryIngredients: ["clams", "potato", "cream"], optionalIngredients: ["onion", "celery", "bacon"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 90 }),
  dish({ cuisine: "american", subCuisine: "newEngland", id: "lobster-roll", english: ["Classic Lobster Rolls", "Lobster Roll"], native: ["Lobster Roll"], region: "New England", description: "Lobster meat served in split-top rolls with lettuce, lemon, and mayonnaise or butter when allowed", primaryIngredients: ["lobster", "roll", "lemon"], optionalIngredients: ["mayonnaise", "celery", "lettuce"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", id: "grapefruit-shrimp-radicchio-tartines", english: ["Grapefruit Shrimp and Radicchio Tartines", "Shrimp Radicchio Tartines"], native: ["Shrimp Tartines"], region: "United States", description: "Charred sourdough tartines topped with shrimp, grapefruit or citrus segments, radicchio, herbs, and scallions", primaryIngredients: ["shrimp", "sourdough", "grapefruit"], optionalIngredients: ["radicchio", "scallion", "dill"], mealTypes: ["breakfast", "lunch"], iconicScore: 82 }),
  dish({ cuisine: "american", id: "citrus-roasted-salmon", english: ["Citrus-Roasted Salmon", "Citrus Roasted Salmon"], native: ["Citrus Roasted Salmon"], region: "United States", description: "Salmon roasted with orange, lemon, herbs, and olive oil on a sheet pan", primaryIngredients: ["salmon", "orange", "lemon"], optionalIngredients: ["thyme", "olive oil", "garlic"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "easy-baked-salmon", english: ["Easy Baked Salmon"], native: ["Easy Baked Salmon"], region: "United States", description: "Simple oven-baked salmon fillets with paprika, herbs, lemon, and olive oil", primaryIngredients: ["salmon", "lemon", "herbs"], optionalIngredients: ["paprika", "garlic", "olive oil"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "baked-tilapia-lemon", english: ["Baked Tilapia with Lemon", "Lemon Baked Tilapia"], native: ["Baked Tilapia"], region: "United States", description: "Tilapia fillets baked with lemon, tomatoes, herbs, and optional feta only when dairy is allowed", primaryIngredients: ["tilapia", "lemon", "tomato"], optionalIngredients: ["herbs", "feta", "olive oil"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "fried-tilapia", english: ["Fried Tilapia"], native: ["Fried Tilapia"], region: "United States", description: "Golden pan-fried tilapia fillets with lemon and parsley", primaryIngredients: ["tilapia", "flour", "lemon"], optionalIngredients: ["parsley", "paprika", "oil"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "macaroni-and-cheese", english: ["Macaroni and Cheese"], native: ["Mac and Cheese"], region: "United States", description: "Macaroni baked or stirred with cheese sauce", primaryIngredients: ["macaroni", "cheese", "milk"], optionalIngredients: ["butter", "breadcrumbs", "mustard"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 90 }),
  dish({ cuisine: "american", id: "meatloaf", english: ["Meatloaf"], native: ["Meatloaf"], region: "United States", description: "Baked seasoned ground meat loaf with glaze", primaryIngredients: ["ground beef", "breadcrumbs", "egg"], optionalIngredients: ["ketchup", "onion", "milk"], mealTypes: ["dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "orange-beef-lettuce-wraps", english: ["Orange Beef Lettuce Wraps", "Ground Beef Lettuce Wraps"], native: ["Orange Beef Lettuce Wraps"], region: "United States", description: "Lettuce cups filled with crumbled ground beef, carrot, scallion, rice only when listed, and orange-soy style glaze", primaryIngredients: ["ground beef", "lettuce", "orange sauce"], optionalIngredients: ["carrot", "scallion", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "ground-beef-zucchini-boats", english: ["Ground Beef Zucchini Boats", "Stuffed Zucchini Boats"], native: ["Ground Beef Zucchini Boats"], region: "United States", description: "Hollowed zucchini halves stuffed with ground beef, peppers, tomato sauce, and cheese or dairy-free topping only when allowed", primaryIngredients: ["zucchini", "ground beef", "tomato sauce"], optionalIngredients: ["pepper", "cheese", "parsley"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "cheesy-ground-beef-cauliflower-casserole", english: ["Cheesy Ground Beef and Cauliflower Casserole", "Ground Beef Cauliflower Casserole"], native: ["Ground Beef Cauliflower Casserole"], region: "United States", description: "Skillet or casserole of crumbled ground beef, cauliflower florets, peppers, and melted cheese or dairy-free topping when allowed", primaryIngredients: ["ground beef", "cauliflower", "pepper"], optionalIngredients: ["cheese", "jalapeno", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 83 }),
  dish({ cuisine: "american", id: "keto-ground-beef-worcestershire", english: ["Keto Ground Beef with Worcestershire", "Ground Beef Worcestershire Skillet"], native: ["Ground Beef Worcestershire Skillet"], region: "United States", description: "Savory crumbled ground beef skillet with onion, peas, carrots, mushrooms, and Worcestershire-style sauce", primaryIngredients: ["ground beef", "onion", "worcestershire sauce"], optionalIngredients: ["peas", "carrot", "mushrooms"], mealTypes: ["lunch", "dinner"], iconicScore: 82 }),
  dish({ cuisine: "american", id: "easy-beef-pot-roast", english: ["Easy Beef Pot Roast", "Beef Pot Roast"], native: ["Beef Pot Roast"], region: "United States", description: "Slow-braised beef roast with potatoes, carrots, onion, herbs, and pan juices", primaryIngredients: ["beef roast", "potato", "carrot"], optionalIngredients: ["onion", "thyme", "rosemary"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", id: "garlic-butter-steak-shrimp", english: ["Garlic Butter Steak and Shrimp", "Steak and Shrimp"], native: ["Steak and Shrimp"], region: "United States", description: "Seared steak with shrimp in garlic butter or olive-oil garlic sauce, herbs, and lemon when listed", primaryIngredients: ["steak", "shrimp", "garlic"], optionalIngredients: ["butter", "olive oil", "parsley", "lemon"], mealTypes: ["lunch", "dinner"], iconicScore: 87 }),
  dish({ cuisine: "american", id: "steak-creamy-garlic-sauce", english: ["Steak with Creamy Garlic Sauce", "Creamy Garlic Steak"], native: ["Creamy Garlic Steak"], region: "United States", description: "Pan-seared steak with a creamy garlic pan sauce, herbs, and dairy-free cream when required", primaryIngredients: ["steak", "garlic", "cream"], optionalIngredients: ["plant cream", "parsley", "pepper"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "coffee-rubbed-strip-steak-chimichurri", english: ["Coffee-Rubbed Strip Steaks with Chimichurri Sauce", "Coffee-Rubbed Strip Steak"], native: ["Coffee-Rubbed Strip Steak"], region: "United States", description: "Strip steak rubbed with coffee and spices, grilled or seared, sliced, and served with bright chimichurri sauce", primaryIngredients: ["strip steak", "coffee rub", "chimichurri"], optionalIngredients: ["parsley", "garlic", "vinegar"], mealTypes: ["lunch", "dinner"], iconicScore: 85 }),
  dish({ cuisine: "american", id: "classic-steak-dinner", english: ["Classic Steak Dinner", "Steak Dinner"], native: ["Steak Dinner"], region: "United States", description: "Sliced or whole seared steak served with potatoes, asparagus, green beans, or simple vegetables when listed", primaryIngredients: ["steak", "potato", "vegetables"], optionalIngredients: ["asparagus", "green beans", "butter", "garlic"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "dry-aged-butter-steak", english: ["Dry-Aged Butter Steak", "Dry Aged Steak"], native: ["Dry Aged Steak"], region: "United States", description: "Thick seared dry-aged steak with browned crust, pan juices, herbs, and butter only when dairy is allowed", primaryIngredients: ["steak", "herbs", "pan juices"], optionalIngredients: ["butter", "garlic", "rosemary"], mealTypes: ["lunch", "dinner"], iconicScore: 85 }),
  dish({ cuisine: "american", id: "chicken-pot-pie", english: ["Chicken Pot Pie"], native: ["Chicken Pot Pie"], region: "United States", description: "Creamy chicken and vegetables baked under pastry", primaryIngredients: ["chicken", "pie crust", "vegetables"], optionalIngredients: ["cream", "peas", "carrot"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", id: "bbq-ribs", english: ["Barbecue Ribs"], native: ["BBQ Ribs"], region: "United States", description: "Slow-cooked pork ribs glazed with barbecue sauce", primaryIngredients: ["pork ribs", "barbecue sauce", "spice rub"], optionalIngredients: ["smoke", "coleslaw"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "american", id: "sticky-bbq-beef-ribs", english: ["Sticky Barbecued Beef Ribs", "Sticky BBQ Beef Ribs"], native: ["Sticky BBQ Beef Ribs"], region: "United States", description: "Sticky glazed beef ribs with barbecue sauce, charred edges, and a glossy finish", primaryIngredients: ["beef ribs", "barbecue sauce", "spice rub"], optionalIngredients: ["pepper jelly", "scallion", "smoke"], mealTypes: ["lunch", "dinner"], iconicScore: 87 }),
  dish({ cuisine: "american", id: "ribs-hot-pepper-jelly-glaze", english: ["Ribs with Hot-Pepper-Jelly Glaze", "Hot Pepper Jelly Ribs"], native: ["Hot Pepper Jelly Ribs"], region: "United States", description: "Glazed ribs with hot pepper jelly, charred edges, herbs, and a sticky sweet-spicy coating", primaryIngredients: ["ribs", "hot pepper jelly", "spice rub"], optionalIngredients: ["herbs", "vinegar", "chili"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "grilled-ribeye-rosemary-potatoes", english: ["Grilled Rib-Eye Steaks with Roasted Rosemary Potatoes", "Rib-Eye Steak with Rosemary Potatoes"], native: ["Rib-Eye Steak with Rosemary Potatoes"], region: "United States", description: "Grilled rib-eye steak served with roasted rosemary potatoes, lemon, and green vegetables when listed", primaryIngredients: ["rib-eye steak", "potato", "rosemary"], optionalIngredients: ["lemon", "green beans", "garlic"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "sausage-mixed-grill", english: ["Sausage Mixed Grill", "Mixed Sausage Grill"], native: ["Sausage Mixed Grill"], region: "United States", description: "Grilled sausages with charred peppers, radicchio, corn, or vegetables on a shared platter", primaryIngredients: ["sausage", "pepper", "grilled vegetables"], optionalIngredients: ["corn", "radicchio", "mustard"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "sheet-pan-sausage-corn-peach-cucumber", english: ["Sheet-Pan Sausage With Corn, Peach, and Cucumber Salad", "Sheet Pan Sausage Corn Peach Salad"], native: ["Sheet Pan Sausage Corn Peach Salad"], region: "United States", description: "Sheet-pan sausage served with corn, peach, cucumber, herbs, and a summer vegetable salad", primaryIngredients: ["sausage", "corn", "cucumber"], optionalIngredients: ["peach", "potato", "herbs"], mealTypes: ["lunch", "dinner"], iconicScore: 83 }),
  dish({ cuisine: "american", id: "polish-lazanki", english: ["Polish Lazanki", "Cabbage Pasta with Mushrooms and Kielbasa"], native: ["Lazanki"], region: "Polish-American", description: "Cabbage pasta with mushrooms, kielbasa or sausage when allowed, dill, and sour cream or dairy-free topping when needed", primaryIngredients: ["pasta", "cabbage", "mushrooms"], optionalIngredients: ["kielbasa", "dill", "sour cream", "plant yogurt"], mealTypes: ["lunch", "dinner"], iconicScore: 82 }),
  dish({ cuisine: "american", subCuisine: "texMexAmerican", id: "chili-con-carne", english: ["Chili Con Carne"], native: ["Chili"], region: "Texas", description: "Beef chili with dried chilies, spices, and often beans", primaryIngredients: ["beef", "chili", "tomato"], optionalIngredients: ["beans", "onion", "cheese"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", id: "buffalo-wings", english: ["Buffalo Wings"], native: ["Buffalo Wings"], region: "Buffalo, New York", description: "Chicken wings tossed in hot sauce and butter", primaryIngredients: ["chicken wings", "hot sauce", "butter"], optionalIngredients: ["celery", "blue cheese"], mealTypes: ["snack", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "american", id: "pancakes", english: ["American Pancakes"], native: ["Pancakes"], region: "United States", description: "Fluffy griddle cakes served with butter and syrup", primaryIngredients: ["flour", "egg", "milk"], optionalIngredients: ["maple syrup", "butter", "blueberries"], mealTypes: ["breakfast"], iconicScore: 90 }),
  dish({ cuisine: "american", id: "vegan-pancakes", english: ["Vegan Pancakes"], native: ["Vegan Pancakes"], region: "United States", description: "Fluffy pancakes made with oat milk, almond milk, or coconut milk instead of dairy and eggs", primaryIngredients: ["flour", "plant milk", "baking powder"], optionalIngredients: ["maple syrup", "blueberries", "banana"], mealTypes: ["breakfast"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "black-bean-burger", english: ["Black Bean Burger"], native: ["Black Bean Burger"], region: "United States", description: "Vegetarian burger patty made with black beans, spices, onion, and breadcrumbs or oats", primaryIngredients: ["black beans", "bun", "onion"], optionalIngredients: ["oats", "lettuce", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", subCuisine: "texMexAmerican", id: "southwestern-pinto-bean-burger", english: ["Southwestern Pinto Bean Burgers", "Pinto Bean Burger"], native: ["Pinto Bean Burger"], region: "American Southwest", description: "Vegetarian pinto bean burger patty with chili spices, onion, tomato, lettuce, and avocado or salsa", primaryIngredients: ["pinto beans", "bun", "chili spices"], optionalIngredients: ["avocado", "tomato", "lettuce", "salsa"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "broccoli-soup-plant-milk", english: ["Dairy-Free Broccoli Soup"], native: ["Dairy-Free Broccoli Soup"], region: "United States", description: "Creamy broccoli soup using oat milk, almond milk, or coconut milk instead of dairy cream", primaryIngredients: ["broccoli", "plant milk", "onion"], optionalIngredients: ["potato", "garlic", "nutritional yeast"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "stuffed-bell-peppers-vegan", english: ["Vegan Stuffed Bell Peppers"], native: ["Vegan Stuffed Bell Peppers"], region: "United States", description: "Bell peppers stuffed with beans, vegetables, tomato, and grains such as quinoa or rice", primaryIngredients: ["bell pepper", "beans", "quinoa"], optionalIngredients: ["tomato", "corn", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "cauliflower-pizza-breadsticks", english: ["Low Carb Cheesy Cauliflower Pizza Breadsticks", "Cauliflower Pizza Breadsticks"], native: ["Cauliflower Pizza Breadsticks"], region: "United States", description: "Cauliflower-crust pizza breadsticks baked with tomato sauce and cheese or dairy-free cheese when required", primaryIngredients: ["cauliflower", "tomato sauce", "cheese"], optionalIngredients: ["dairy-free cheese", "herbs", "garlic"], mealTypes: ["lunch", "dinner", "snack"], iconicScore: 83 }),
  dish({ cuisine: "american", id: "low-carb-eggplant-lasagna", english: ["Low Carb Easy Eggplant Lasagna", "Eggplant Lasagna"], native: ["Eggplant Lasagna"], region: "United States", description: "Layered eggplant slices with tomato sauce and cheese or tofu ricotta, using eggplant instead of pasta sheets", primaryIngredients: ["eggplant", "tomato sauce", "tofu ricotta"], optionalIngredients: ["dairy-free cheese", "basil", "spinach"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "low-carb-roasted-veggie-pizza", english: ["Low Carb Roasted Veggie Pizza", "Roasted Veggie Pizza"], native: ["Roasted Veggie Pizza"], region: "United States", description: "Low-carb vegetable-crust or casserole-style pizza topped with roasted vegetables, tomato sauce, and dairy-free cheese when needed", primaryIngredients: ["roasted vegetables", "tomato sauce", "vegetable crust"], optionalIngredients: ["dairy-free cheese", "zucchini", "pepper", "onion"], mealTypes: ["lunch", "dinner"], iconicScore: 83 }),
  dish({ cuisine: "american", id: "roasted-vegetable-stuffed-shells", english: ["Roasted Vegetables Stuffed Shells", "Roasted Vegetable Stuffed Pasta Shells"], native: ["Roasted Vegetable Stuffed Shells"], region: "Italian-American", description: "Large pasta shells filled with roasted vegetables and tomato marinara; use tofu ricotta or omit cheese for vegan and dairy-free plans", primaryIngredients: ["pasta shells", "roasted vegetables", "tomato sauce"], optionalIngredients: ["tofu ricotta", "zucchini", "pepper", "spinach"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "zucchini-veggie-bake", english: ["Zucchini Veggie Bake", "Zucchini Vegetable Bake"], native: ["Zucchini Veggie Bake"], region: "United States", description: "Layered zucchini, tomato, peppers, onion, and herbs baked into a colorful vegetable casserole without meat", primaryIngredients: ["zucchini", "tomato", "pepper"], optionalIngredients: ["onion", "herbs", "nutritional yeast"], mealTypes: ["lunch", "dinner"], iconicScore: 82 }),
  dish({ cuisine: "american", id: "strawberry-smoothie-bowl", english: ["Strawberry Smoothie Bowl"], native: ["Strawberry Smoothie Bowl"], region: "United States", description: "Thick strawberry smoothie bowl topped with banana, berries, seeds, oats, or nuts", primaryIngredients: ["strawberry", "banana", "plant milk"], optionalIngredients: ["chia seeds", "oats", "nuts"], mealTypes: ["breakfast", "snack"], iconicScore: 82 }),
  dish({ cuisine: "american", id: "french-toast", english: ["French Toast"], native: ["French Toast"], region: "United States", description: "Bread soaked in egg custard and griddled", primaryIngredients: ["bread", "egg", "milk"], optionalIngredients: ["cinnamon", "syrup", "butter"], mealTypes: ["breakfast"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "cobb-salad", english: ["Cobb Salad"], native: ["Cobb Salad"], region: "California", description: "Chopped salad with chicken, bacon, egg, avocado, tomato, and blue cheese", primaryIngredients: ["chicken", "bacon", "egg"], optionalIngredients: ["avocado", "tomato", "blue cheese"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "apple-pie", english: ["Apple Pie"], native: ["Apple Pie"], region: "United States", description: "Double-crust pie filled with spiced apples", primaryIngredients: ["apple", "pie crust", "sugar"], optionalIngredients: ["cinnamon", "butter"], mealTypes: ["dessert"], iconicScore: 94 }),
  dish({ cuisine: "american", id: "brownies", english: ["Brownies"], native: ["Brownies"], region: "United States", description: "Dense chocolate squares baked with cocoa or melted chocolate", primaryIngredients: ["chocolate", "flour", "egg"], optionalIngredients: ["butter", "walnuts", "sugar"], mealTypes: ["dessert"], iconicScore: 88 })
];
