import type { CuisineDish, CuisineKey, MealType, SubCuisineKey } from "./types";

type DishInput = {
  cuisine: CuisineKey;
  description: string;
  english: string[];
  id: string;
  iconicScore: number;
  mealTypes: MealType[];
  native?: string[];
  optionalIngredients: string[];
  primaryIngredients: string[];
  region: string;
  subCuisine?: SubCuisineKey;
};

function dish(input: DishInput): CuisineDish {
  return {
    cuisine: input.cuisine,
    description: input.description,
    iconicScore: input.iconicScore,
    id: input.id,
    mealTypes: input.mealTypes,
    names: {
      english: input.english,
      native: input.native ?? input.english
    },
    optionalIngredients: input.optionalIngredients,
    primaryIngredients: input.primaryIngredients,
    region: input.region,
    subCuisine: input.subCuisine
  };
}

export const INDIAN_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "dal-tadka", english: ["Dal Tadka"], native: ["Dal Tadka"], region: "North India", description: "Yellow lentils tempered with ghee, cumin, garlic, and chilies", primaryIngredients: ["lentils", "ghee", "cumin"], optionalIngredients: ["garlic", "chili", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 92 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "chana-masala", english: ["Chana Masala"], native: ["Chana Masala"], region: "North India", description: "Chickpeas simmered with onion, tomato, ginger, and garam masala", primaryIngredients: ["chickpeas", "tomato", "onion"], optionalIngredients: ["ginger", "garam masala", "cilantro"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "rajma", english: ["Rajma"], native: ["Rajma"], region: "Punjab", description: "Kidney bean curry served with rice", primaryIngredients: ["kidney beans", "tomato", "onion"], optionalIngredients: ["ginger", "garlic", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "aloo-gobi", english: ["Aloo Gobi"], native: ["Aloo Gobi"], region: "North India", description: "Dry cauliflower and potato sabzi with turmeric and cumin", primaryIngredients: ["potato", "cauliflower", "turmeric"], optionalIngredients: ["cumin", "ginger", "cilantro"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "palak-paneer", english: ["Palak Paneer"], native: ["Palak Paneer"], region: "North India", description: "Paneer cubes in spiced spinach gravy", primaryIngredients: ["spinach", "paneer", "cream"], optionalIngredients: ["garlic", "ginger", "garam masala"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "paneer-butter-masala", english: ["Paneer Butter Masala"], native: ["Paneer Butter Masala"], region: "North India", description: "Paneer in buttery tomato-cashew gravy", primaryIngredients: ["paneer", "tomato", "butter"], optionalIngredients: ["cream", "cashew", "fenugreek"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "butter-chicken", english: ["Butter Chicken", "Murgh Makhani"], native: ["Murgh Makhani"], region: "Delhi", description: "Tandoori chicken simmered in buttery tomato gravy", primaryIngredients: ["chicken", "tomato", "butter"], optionalIngredients: ["cream", "fenugreek", "garam masala"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "chicken-tikka-masala", english: ["Chicken Tikka Masala"], native: ["Chicken Tikka Masala"], region: "North Indian diaspora", description: "Chicken tikka in spiced tomato cream sauce", primaryIngredients: ["chicken", "tomato", "cream"], optionalIngredients: ["yogurt", "garam masala", "ginger"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "masala-dosa", english: ["Masala Dosa"], native: ["Masala Dosa"], region: "South India", description: "Crisp rice-lentil crepe filled with spiced potatoes", primaryIngredients: ["rice batter", "lentils", "potato"], optionalIngredients: ["mustard seed", "curry leaves", "chutney"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "idli-sambar", english: ["Idli Sambar"], native: ["Idli Sambar"], region: "South India", description: "Steamed rice-lentil cakes served with lentil vegetable stew", primaryIngredients: ["rice batter", "lentils", "sambar"], optionalIngredients: ["coconut chutney", "curry leaves"], mealTypes: ["breakfast", "lunch"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "vada-sambar", english: ["Vada Sambar"], native: ["Vada Sambar"], region: "South India", description: "Fried lentil doughnuts served with sambar", primaryIngredients: ["urad dal", "sambar", "curry leaves"], optionalIngredients: ["coconut chutney", "chili"], mealTypes: ["breakfast", "snack"], iconicScore: 86 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "uttapam", english: ["Uttapam"], native: ["Uttapam"], region: "South India", description: "Thick rice-lentil pancake with onion, chili, and tomato", primaryIngredients: ["rice batter", "onion", "tomato"], optionalIngredients: ["chili", "coconut chutney"], mealTypes: ["breakfast", "lunch"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "avial", english: ["Avial"], native: ["Avial"], region: "Kerala", description: "Mixed vegetables in coconut-yogurt sauce", primaryIngredients: ["mixed vegetables", "coconut", "yogurt"], optionalIngredients: ["curry leaves", "cumin", "green chili"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "kerala-fish-curry", english: ["Kerala Fish Curry"], native: ["Meen Curry"], region: "Kerala", description: "Fish simmered with coconut, chili, curry leaves, and tamarind", primaryIngredients: ["fish", "coconut milk", "tamarind"], optionalIngredients: ["curry leaves", "chili", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "southIndian", id: "hyderabadi-biryani", english: ["Hyderabadi Biryani"], native: ["Hyderabadi Biryani"], region: "Hyderabad", description: "Layered rice and marinated meat cooked with saffron and spices", primaryIngredients: ["rice", "chicken", "yogurt"], optionalIngredients: ["saffron", "mint", "fried onion"], mealTypes: ["lunch", "dinner"], iconicScore: 95 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "lamb-rogan-josh", english: ["Rogan Josh"], native: ["Rogan Josh"], region: "Kashmir", description: "Aromatic lamb curry with Kashmiri chili and warm spices", primaryIngredients: ["lamb", "yogurt", "kashmiri chili"], optionalIngredients: ["ginger", "fennel", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "pav-bhaji", english: ["Pav Bhaji"], native: ["Pav Bhaji"], region: "Mumbai", description: "Mashed spiced vegetable curry served with buttered bread rolls", primaryIngredients: ["potato", "mixed vegetables", "bread"], optionalIngredients: ["butter", "onion", "cilantro"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 88 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "vada-pav", english: ["Vada Pav"], native: ["Vada Pav"], region: "Mumbai", description: "Spiced potato fritter in a bread roll with chutneys", primaryIngredients: ["potato", "bread", "chutney"], optionalIngredients: ["chili", "garlic", "gram flour"], mealTypes: ["snack", "street_food"], iconicScore: 90 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "poha", english: ["Poha"], native: ["Poha"], region: "Maharashtra", description: "Flattened rice cooked with mustard seed, onion, turmeric, and peanuts", primaryIngredients: ["flattened rice", "onion", "turmeric"], optionalIngredients: ["peanuts", "curry leaves", "lemon"], mealTypes: ["breakfast", "snack"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "westIndian", id: "dhokla", english: ["Dhokla"], native: ["Dhokla"], region: "Gujarat", description: "Steamed fermented gram flour cakes with mustard tempering", primaryIngredients: ["gram flour", "yogurt", "mustard seed"], optionalIngredients: ["curry leaves", "green chili"], mealTypes: ["breakfast", "snack"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "eastIndian", id: "macher-jhol", english: ["Macher Jhol"], native: ["Macher Jhol"], region: "Bengal", description: "Light Bengali fish curry with potato, tomato, and mustard oil", primaryIngredients: ["fish", "potato", "mustard oil"], optionalIngredients: ["tomato", "turmeric", "rice"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "indian", subCuisine: "eastIndian", id: "litti-chokha", english: ["Litti Chokha"], native: ["Litti Chokha"], region: "Bihar", description: "Roasted wheat balls filled with sattu served with mashed vegetables", primaryIngredients: ["wheat flour", "sattu", "eggplant"], optionalIngredients: ["potato", "tomato", "mustard oil"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 82 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "samosa", english: ["Samosa"], native: ["Samosa"], region: "India", description: "Fried pastry filled with spiced potatoes and peas", primaryIngredients: ["flour", "potato", "peas"], optionalIngredients: ["cumin", "chutney", "chili"], mealTypes: ["snack", "street_food"], iconicScore: 92 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "kheer", english: ["Kheer"], native: ["Kheer"], region: "India", description: "Rice pudding with milk, sugar, cardamom, and nuts", primaryIngredients: ["rice", "milk", "sugar"], optionalIngredients: ["cardamom", "nuts", "saffron"], mealTypes: ["dessert"], iconicScore: 84 }),
  dish({ cuisine: "indian", subCuisine: "northIndian", id: "gulab-jamun", english: ["Gulab Jamun"], native: ["Gulab Jamun"], region: "North India", description: "Milk-solid dumplings soaked in cardamom syrup", primaryIngredients: ["milk solids", "flour", "syrup"], optionalIngredients: ["cardamom", "rose water"], mealTypes: ["dessert"], iconicScore: 90 })
];

export const THAI_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pad-thai", english: ["Pad Thai"], native: ["Pad Thai"], region: "Central Thailand", description: "Stir-fried rice noodles with tamarind, egg, tofu or shrimp, and peanuts", primaryIngredients: ["rice noodles", "tamarind", "egg"], optionalIngredients: ["shrimp", "tofu", "peanuts"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 96 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "tom-yum-goong", english: ["Tom Yum Goong"], native: ["Tom Yum Goong"], region: "Central Thailand", description: "Hot-sour shrimp soup with lemongrass, galangal, and lime leaf", primaryIngredients: ["shrimp", "lemongrass", "lime"], optionalIngredients: ["galangal", "kaffir lime leaf", "chili"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 94 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "green-curry-chicken", english: ["Thai Green Curry Chicken", "Gaeng Keow Wan Gai"], native: ["Gaeng Keow Wan Gai"], region: "Central Thailand", description: "Chicken simmered in green curry paste and coconut milk", primaryIngredients: ["chicken", "green curry paste", "coconut milk"], optionalIngredients: ["eggplant", "basil", "fish sauce"], mealTypes: ["lunch", "dinner"], iconicScore: 92 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "red-curry", english: ["Thai Red Curry"], native: ["Gaeng Phed"], region: "Central Thailand", description: "Red curry paste simmered with coconut milk and meat or vegetables", primaryIngredients: ["red curry paste", "coconut milk", "meat"], optionalIngredients: ["bamboo shoots", "basil", "fish sauce"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "massaman-curry", english: ["Massaman Curry"], native: ["Gaeng Massaman"], region: "Central Thailand", description: "Mild Muslim-influenced curry with potato, peanuts, and warm spices", primaryIngredients: ["beef", "potato", "coconut milk"], optionalIngredients: ["peanuts", "tamarind", "cinnamon"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "panang-curry", english: ["Panang Curry"], native: ["Panang Curry"], region: "Central Thailand", description: "Thick coconut curry with red curry paste and kaffir lime leaf", primaryIngredients: ["meat", "panang curry paste", "coconut milk"], optionalIngredients: ["peanuts", "lime leaf", "basil"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "thai", subCuisine: "northeasternThai", id: "som-tam", english: ["Som Tam", "Green Papaya Salad"], native: ["Som Tam"], region: "Isan", description: "Pounded green papaya salad with lime, chili, fish sauce, and peanuts", primaryIngredients: ["green papaya", "lime", "chili"], optionalIngredients: ["fish sauce", "peanuts", "tomato"], mealTypes: ["lunch", "side", "street_food"], iconicScore: 94 }),
  dish({ cuisine: "thai", subCuisine: "northeasternThai", id: "larb-gai", english: ["Larb Gai"], native: ["Larb Gai"], region: "Isan", description: "Minced chicken salad with toasted rice powder, lime, chili, and herbs", primaryIngredients: ["ground chicken", "lime", "toasted rice"], optionalIngredients: ["mint", "fish sauce", "chili"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "northeasternThai", id: "nam-tok", english: ["Nam Tok"], native: ["Nam Tok"], region: "Isan", description: "Grilled meat salad with lime, chili, herbs, and toasted rice powder", primaryIngredients: ["grilled beef", "lime", "toasted rice"], optionalIngredients: ["mint", "fish sauce", "chili"], mealTypes: ["lunch", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pad-krapow-gai", english: ["Pad Krapow Gai", "Thai Basil Chicken"], native: ["Pad Krapow Gai"], region: "Central Thailand", description: "Stir-fried minced chicken with holy basil and chilies", primaryIngredients: ["ground chicken", "holy basil", "chili"], optionalIngredients: ["garlic", "fish sauce", "egg"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 92 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "khao-pad", english: ["Khao Pad", "Thai Fried Rice"], native: ["Khao Pad"], region: "Thailand", description: "Thai fried rice with egg, onion, and a protein", primaryIngredients: ["rice", "egg", "onion"], optionalIngredients: ["shrimp", "chicken", "lime"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "pad-see-ew", english: ["Pad See Ew"], native: ["Pad See Ew"], region: "Central Thailand", description: "Wide rice noodles stir-fried with dark soy sauce, egg, and Chinese broccoli", primaryIngredients: ["wide rice noodles", "egg", "soy sauce"], optionalIngredients: ["chinese broccoli", "chicken", "beef"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "rad-na", english: ["Rad Na"], native: ["Rad Na"], region: "Central Thailand", description: "Wide noodles topped with savory gravy and Chinese broccoli", primaryIngredients: ["wide rice noodles", "gravy", "chinese broccoli"], optionalIngredients: ["pork", "chicken", "soy sauce"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "northernThai", id: "khao-soi", english: ["Khao Soi"], native: ["Khao Soi"], region: "Northern Thailand", description: "Coconut curry noodle soup with chicken and crispy noodles", primaryIngredients: ["egg noodles", "chicken", "coconut milk"], optionalIngredients: ["curry paste", "pickled mustard greens", "lime"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 92 }),
  dish({ cuisine: "thai", subCuisine: "southernThai", id: "gaeng-som", english: ["Gaeng Som"], native: ["Gaeng Som"], region: "Southern Thailand", description: "Sour orange curry with fish or shrimp and vegetables", primaryIngredients: ["fish", "tamarind", "curry paste"], optionalIngredients: ["vegetables", "shrimp", "lime"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "tom-kha-gai", english: ["Tom Kha Gai"], native: ["Tom Kha Gai"], region: "Central Thailand", description: "Coconut chicken soup with galangal, lemongrass, and lime", primaryIngredients: ["chicken", "coconut milk", "galangal"], optionalIngredients: ["lemongrass", "lime", "mushroom"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 90 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "satay-gai", english: ["Chicken Satay", "Satay Gai"], native: ["Satay Gai"], region: "Thailand", description: "Grilled marinated chicken skewers with peanut sauce", primaryIngredients: ["chicken", "peanut sauce", "turmeric"], optionalIngredients: ["coconut milk", "cucumber relish"], mealTypes: ["snack", "street_food", "dinner"], iconicScore: 86 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "tod-man-pla", english: ["Tod Man Pla", "Thai Fish Cakes"], native: ["Tod Man Pla"], region: "Thailand", description: "Fried fish cakes with red curry paste and lime leaf", primaryIngredients: ["fish", "red curry paste", "lime leaf"], optionalIngredients: ["green beans", "cucumber relish"], mealTypes: ["snack", "side"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "yam-woon-sen", english: ["Yam Woon Sen", "Glass Noodle Salad"], native: ["Yam Woon Sen"], region: "Thailand", description: "Spicy glass noodle salad with lime, chili, herbs, and seafood or pork", primaryIngredients: ["glass noodles", "lime", "chili"], optionalIngredients: ["shrimp", "ground pork", "cilantro"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "thai", subCuisine: "centralThai", id: "mango-sticky-rice", english: ["Mango Sticky Rice"], native: ["Khao Niao Mamuang"], region: "Thailand", description: "Sweet coconut sticky rice served with ripe mango", primaryIngredients: ["sticky rice", "mango", "coconut milk"], optionalIngredients: ["sugar", "sesame"], mealTypes: ["dessert"], iconicScore: 94 })
];

export const MEDITERRANEAN_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "greek-salad", english: ["Greek Salad", "Horiatiki"], native: ["Horiatiki"], region: "Greece", description: "Tomato, cucumber, onion, olives, and feta with olive oil", primaryIngredients: ["tomato", "cucumber", "feta"], optionalIngredients: ["olive", "onion", "oregano"], mealTypes: ["lunch", "side"], iconicScore: 92 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "moussaka", english: ["Moussaka"], native: ["Moussaka"], region: "Greece", description: "Layered eggplant, spiced meat sauce, and bechamel", primaryIngredients: ["eggplant", "ground meat", "bechamel"], optionalIngredients: ["potato", "tomato", "cinnamon"], mealTypes: ["lunch", "dinner"], iconicScore: 92 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "spanakopita", english: ["Spanakopita"], native: ["Spanakopita"], region: "Greece", description: "Spinach and feta pie baked in phyllo", primaryIngredients: ["phyllo", "spinach", "feta"], optionalIngredients: ["dill", "egg", "onion"], mealTypes: ["breakfast", "lunch", "snack"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "souvlaki", english: ["Souvlaki"], native: ["Souvlaki"], region: "Greece", description: "Grilled marinated meat skewers often served with pita and tzatziki", primaryIngredients: ["meat", "pita", "tzatziki"], optionalIngredients: ["lemon", "oregano", "tomato"], mealTypes: ["lunch", "dinner", "street_food"], iconicScore: 90 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "tzatziki", english: ["Tzatziki"], native: ["Tzatziki"], region: "Greece", description: "Yogurt cucumber dip with garlic, dill, and olive oil", primaryIngredients: ["yogurt", "cucumber", "garlic"], optionalIngredients: ["dill", "olive oil", "lemon"], mealTypes: ["side", "snack"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", subCuisine: "greek", id: "dolmades", english: ["Dolmades"], native: ["Dolmades"], region: "Greece", description: "Grape leaves stuffed with rice, herbs, and sometimes meat", primaryIngredients: ["grape leaves", "rice", "herbs"], optionalIngredients: ["ground meat", "lemon", "olive oil"], mealTypes: ["lunch", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "paella-valenciana", english: ["Paella Valenciana"], native: ["Paella Valenciana"], region: "Valencia", description: "Saffron rice cooked with chicken, rabbit, beans, and vegetables", primaryIngredients: ["rice", "saffron", "chicken"], optionalIngredients: ["rabbit", "green beans", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "gazpacho", english: ["Gazpacho"], native: ["Gazpacho"], region: "Andalusia", description: "Cold blended tomato soup with cucumber, pepper, and olive oil", primaryIngredients: ["tomato", "cucumber", "olive oil"], optionalIngredients: ["pepper", "bread", "garlic"], mealTypes: ["lunch", "soup"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "tortilla-espanola", english: ["Tortilla Espanola", "Spanish Tortilla"], native: ["Tortilla Espanola"], region: "Spain", description: "Thick omelet with potatoes and onions", primaryIngredients: ["egg", "potato", "onion"], optionalIngredients: ["olive oil", "salt"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "pan-con-tomate", english: ["Pan Con Tomate"], native: ["Pan Con Tomate"], region: "Catalonia", description: "Toasted bread rubbed with tomato, garlic, and olive oil", primaryIngredients: ["bread", "tomato", "olive oil"], optionalIngredients: ["garlic", "salt"], mealTypes: ["breakfast", "snack", "side"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", subCuisine: "spanish", id: "patatas-bravas", english: ["Patatas Bravas"], native: ["Patatas Bravas"], region: "Spain", description: "Fried potatoes served with spicy bravas sauce", primaryIngredients: ["potato", "tomato sauce", "paprika"], optionalIngredients: ["garlic aioli", "olive oil"], mealTypes: ["side", "snack"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "fattoush-mediterranean", english: ["Fattoush"], native: ["Fattoush"], region: "Levant", description: "Chopped salad with toasted pita, sumac, and lemon dressing", primaryIngredients: ["pita", "tomato", "cucumber"], optionalIngredients: ["sumac", "lettuce", "mint"], mealTypes: ["lunch", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "hummus-mediterranean", english: ["Hummus"], native: ["Hummus"], region: "Eastern Mediterranean", description: "Chickpea tahini dip with lemon and olive oil", primaryIngredients: ["chickpeas", "tahini", "lemon"], optionalIngredients: ["olive oil", "garlic", "paprika"], mealTypes: ["breakfast", "snack", "side"], iconicScore: 92 }),
  dish({ cuisine: "mediterranean", subCuisine: "levantineMediterranean", id: "shakshuka-mediterranean", english: ["Shakshuka"], native: ["Shakshuka"], region: "Mediterranean", description: "Eggs poached in tomato and pepper sauce", primaryIngredients: ["egg", "tomato", "pepper"], optionalIngredients: ["onion", "garlic", "cumin"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", id: "ratatouille", english: ["Ratatouille"], native: ["Ratatouille"], region: "Provence", description: "Vegetable stew of eggplant, zucchini, pepper, and tomato", primaryIngredients: ["eggplant", "zucchini", "tomato"], optionalIngredients: ["pepper", "olive oil", "herbs"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 86 }),
  dish({ cuisine: "mediterranean", id: "nicoise-salad", english: ["Nicoise Salad"], native: ["Salade Nicoise"], region: "Nice", description: "Tuna, egg, olives, green beans, tomato, and potatoes", primaryIngredients: ["tuna", "egg", "green beans"], optionalIngredients: ["olive", "potato", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", id: "bouillabaisse", english: ["Bouillabaisse"], native: ["Bouillabaisse"], region: "Marseille", description: "Mediterranean fish stew with saffron, fennel, and rouille", primaryIngredients: ["fish", "saffron", "fennel"], optionalIngredients: ["shellfish", "tomato", "bread"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 88 }),
  dish({ cuisine: "mediterranean", id: "caponata", english: ["Caponata"], native: ["Caponata"], region: "Sicily", description: "Sweet-sour eggplant relish with celery, capers, and tomato", primaryIngredients: ["eggplant", "tomato", "capers"], optionalIngredients: ["celery", "olive", "vinegar"], mealTypes: ["side", "lunch"], iconicScore: 84 }),
  dish({ cuisine: "mediterranean", id: "baked-feta", english: ["Baked Feta"], native: ["Baked Feta"], region: "Eastern Mediterranean", description: "Feta baked with tomatoes, olive oil, and herbs", primaryIngredients: ["feta", "tomato", "olive oil"], optionalIngredients: ["oregano", "pepper", "bread"], mealTypes: ["lunch", "side"], iconicScore: 80 }),
  dish({ cuisine: "mediterranean", id: "seafood-orzo", english: ["Seafood Orzo"], native: ["Seafood Orzo"], region: "Mediterranean coast", description: "Orzo cooked with seafood, tomato, herbs, and olive oil", primaryIngredients: ["orzo", "seafood", "tomato"], optionalIngredients: ["olive oil", "parsley", "lemon"], mealTypes: ["lunch", "dinner"], iconicScore: 80 })
];

export const AMERICAN_DISHES: readonly CuisineDish[] = [
  dish({ cuisine: "american", id: "hamburger", english: ["Hamburger"], native: ["Hamburger"], region: "United States", description: "Ground beef patty served in a bun with classic toppings", primaryIngredients: ["ground beef", "bun", "lettuce"], optionalIngredients: ["cheese", "tomato", "pickle"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "american", id: "cheeseburger", english: ["Cheeseburger"], native: ["Cheeseburger"], region: "United States", description: "Burger with melted cheese and classic condiments", primaryIngredients: ["ground beef", "bun", "cheese"], optionalIngredients: ["pickle", "onion", "ketchup"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "american", subCuisine: "southernAmerican", id: "fried-chicken", english: ["Fried Chicken"], native: ["Fried Chicken"], region: "American South", description: "Seasoned chicken pieces dredged and fried crisp", primaryIngredients: ["chicken", "flour", "buttermilk"], optionalIngredients: ["paprika", "hot sauce", "oil"], mealTypes: ["lunch", "dinner"], iconicScore: 94 }),
  dish({ cuisine: "american", subCuisine: "southernAmerican", id: "biscuits-and-gravy", english: ["Biscuits and Gravy"], native: ["Biscuits and Gravy"], region: "American South", description: "Buttermilk biscuits topped with sausage gravy", primaryIngredients: ["biscuits", "sausage", "milk"], optionalIngredients: ["flour", "black pepper"], mealTypes: ["breakfast"], iconicScore: 88 }),
  dish({ cuisine: "american", subCuisine: "southernAmerican", id: "shrimp-and-grits", english: ["Shrimp and Grits"], native: ["Shrimp and Grits"], region: "Lowcountry", description: "Shrimp served over creamy corn grits", primaryIngredients: ["shrimp", "grits", "butter"], optionalIngredients: ["bacon", "scallion", "cheese"], mealTypes: ["breakfast", "lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", subCuisine: "cajunCreole", id: "gumbo", english: ["Gumbo"], native: ["Gumbo"], region: "Louisiana", description: "Okra or roux-thickened stew with seafood, chicken, or sausage", primaryIngredients: ["roux", "okra", "sausage"], optionalIngredients: ["shrimp", "chicken", "rice"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 92 }),
  dish({ cuisine: "american", subCuisine: "cajunCreole", id: "jambalaya", english: ["Jambalaya"], native: ["Jambalaya"], region: "Louisiana", description: "One-pot rice dish with sausage, chicken, seafood, and Cajun seasoning", primaryIngredients: ["rice", "sausage", "chicken"], optionalIngredients: ["shrimp", "pepper", "tomato"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "american", subCuisine: "newEngland", id: "clam-chowder", english: ["New England Clam Chowder"], native: ["Clam Chowder"], region: "New England", description: "Creamy clam soup with potatoes and onions", primaryIngredients: ["clams", "potato", "cream"], optionalIngredients: ["onion", "celery", "bacon"], mealTypes: ["lunch", "dinner", "soup"], iconicScore: 90 }),
  dish({ cuisine: "american", subCuisine: "newEngland", id: "lobster-roll", english: ["Lobster Roll"], native: ["Lobster Roll"], region: "New England", description: "Lobster meat served in a split-top roll", primaryIngredients: ["lobster", "roll", "butter"], optionalIngredients: ["mayonnaise", "celery", "lemon"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", id: "macaroni-and-cheese", english: ["Macaroni and Cheese"], native: ["Mac and Cheese"], region: "United States", description: "Macaroni baked or stirred with cheese sauce", primaryIngredients: ["macaroni", "cheese", "milk"], optionalIngredients: ["butter", "breadcrumbs", "mustard"], mealTypes: ["lunch", "dinner", "side"], iconicScore: 90 }),
  dish({ cuisine: "american", id: "meatloaf", english: ["Meatloaf"], native: ["Meatloaf"], region: "United States", description: "Baked seasoned ground meat loaf with glaze", primaryIngredients: ["ground beef", "breadcrumbs", "egg"], optionalIngredients: ["ketchup", "onion", "milk"], mealTypes: ["dinner"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "chicken-pot-pie", english: ["Chicken Pot Pie"], native: ["Chicken Pot Pie"], region: "United States", description: "Creamy chicken and vegetables baked under pastry", primaryIngredients: ["chicken", "pie crust", "vegetables"], optionalIngredients: ["cream", "peas", "carrot"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", id: "bbq-ribs", english: ["Barbecue Ribs"], native: ["BBQ Ribs"], region: "United States", description: "Slow-cooked pork ribs glazed with barbecue sauce", primaryIngredients: ["pork ribs", "barbecue sauce", "spice rub"], optionalIngredients: ["smoke", "coleslaw"], mealTypes: ["lunch", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "american", subCuisine: "texMexAmerican", id: "chili-con-carne", english: ["Chili Con Carne"], native: ["Chili"], region: "Texas", description: "Beef chili with dried chilies, spices, and often beans", primaryIngredients: ["beef", "chili", "tomato"], optionalIngredients: ["beans", "onion", "cheese"], mealTypes: ["lunch", "dinner"], iconicScore: 88 }),
  dish({ cuisine: "american", id: "buffalo-wings", english: ["Buffalo Wings"], native: ["Buffalo Wings"], region: "Buffalo, New York", description: "Chicken wings tossed in hot sauce and butter", primaryIngredients: ["chicken wings", "hot sauce", "butter"], optionalIngredients: ["celery", "blue cheese"], mealTypes: ["snack", "dinner"], iconicScore: 90 }),
  dish({ cuisine: "american", id: "pancakes", english: ["American Pancakes"], native: ["Pancakes"], region: "United States", description: "Fluffy griddle cakes served with butter and syrup", primaryIngredients: ["flour", "egg", "milk"], optionalIngredients: ["maple syrup", "butter", "blueberries"], mealTypes: ["breakfast"], iconicScore: 90 }),
  dish({ cuisine: "american", id: "french-toast", english: ["French Toast"], native: ["French Toast"], region: "United States", description: "Bread soaked in egg custard and griddled", primaryIngredients: ["bread", "egg", "milk"], optionalIngredients: ["cinnamon", "syrup", "butter"], mealTypes: ["breakfast"], iconicScore: 86 }),
  dish({ cuisine: "american", id: "cobb-salad", english: ["Cobb Salad"], native: ["Cobb Salad"], region: "California", description: "Chopped salad with chicken, bacon, egg, avocado, tomato, and blue cheese", primaryIngredients: ["chicken", "bacon", "egg"], optionalIngredients: ["avocado", "tomato", "blue cheese"], mealTypes: ["lunch", "dinner"], iconicScore: 84 }),
  dish({ cuisine: "american", id: "apple-pie", english: ["Apple Pie"], native: ["Apple Pie"], region: "United States", description: "Double-crust pie filled with spiced apples", primaryIngredients: ["apple", "pie crust", "sugar"], optionalIngredients: ["cinnamon", "butter"], mealTypes: ["dessert"], iconicScore: 94 }),
  dish({ cuisine: "american", id: "brownies", english: ["Brownies"], native: ["Brownies"], region: "United States", description: "Dense chocolate squares baked with cocoa or melted chocolate", primaryIngredients: ["chocolate", "flour", "egg"], optionalIngredients: ["butter", "walnuts", "sugar"], mealTypes: ["dessert"], iconicScore: 88 })
];
