export interface CuisineProfile {
  id: string;
  name: string;
  aliases: string[];
  proteins: string[];
  grains: string[];
  vegetables: string[];
  spices: string[];
  herbs: string[];
  techniques: string[];
}

const profile = (input: CuisineProfile) => Object.freeze(input);

/** Stable, import-time reference data. It is not generated by Gemini. */
export const CuisineProfiles: Record<string, CuisineProfile> = Object.freeze({
  egyptian: profile({ id: "egyptian", name: "Egyptian", aliases: ["egypt", "masri"], proteins: ["chicken", "beef", "duck", "fish", "lentils"], grains: ["rice", "freekeh", "pasta"], vegetables: ["molokhia", "okra", "eggplant", "tomato"], spices: ["cumin", "coriander", "cardamom"], herbs: ["parsley", "dill", "cilantro"], techniques: ["stew", "roast", "stuff", "grill"] }),
  turkish: profile({ id: "turkish", name: "Turkish", aliases: ["turkiye", "anatolian"], proteins: ["lamb", "beef", "chicken", "fish", "egg"], grains: ["bulgur", "rice", "bread"], vegetables: ["eggplant", "bell pepper", "tomato", "zucchini"], spices: ["sumac", "paprika", "cumin", "aleppo pepper"], herbs: ["dill", "mint", "parsley"], techniques: ["grill", "bake", "stuff", "braise"] }),
  italian: profile({ id: "italian", name: "Italian", aliases: ["italy", "sicilian", "tuscan"], proteins: ["chicken", "beef", "fish", "shrimp", "beans"], grains: ["pasta", "arborio rice", "bread"], vegetables: ["tomato", "eggplant", "mushroom", "spinach"], spices: ["black pepper", "chili", "nutmeg"], herbs: ["basil", "oregano", "parsley"], techniques: ["braise", "bake", "risotto", "roast"] }),
  greek: profile({ id: "greek", name: "Greek", aliases: ["greece", "hellenic"], proteins: ["chicken", "lamb", "fish", "beans"], grains: ["rice", "orzo", "pita"], vegetables: ["eggplant", "zucchini", "tomato", "spinach"], spices: ["oregano", "cinnamon", "black pepper"], herbs: ["dill", "mint", "parsley"], techniques: ["grill", "bake", "stew", "stuff"] }),
  lebanese: profile({ id: "lebanese", name: "Lebanese", aliases: ["lebanon", "levantine"], proteins: ["chicken", "lamb", "beef", "chickpeas"], grains: ["rice", "bulgur", "pita"], vegetables: ["eggplant", "tomato", "cucumber", "zucchini"], spices: ["sumac", "allspice", "cumin"], herbs: ["parsley", "mint", "cilantro"], techniques: ["grill", "stuff", "stew", "blend"] }),
  syrian: profile({ id: "syrian", name: "Syrian", aliases: ["syria", "levantine"], proteins: ["chicken", "lamb", "beef", "chickpeas"], grains: ["rice", "bulgur", "flatbread"], vegetables: ["eggplant", "pepper", "tomato", "zucchini"], spices: ["aleppo pepper", "allspice", "cumin"], herbs: ["parsley", "mint", "cilantro"], techniques: ["grill", "stuff", "bake", "stew"] }),
  indian: profile({ id: "indian", name: "Indian", aliases: ["india", "south asian"], proteins: ["chicken", "lamb", "fish", "paneer", "lentils"], grains: ["basmati rice", "naan", "lentils"], vegetables: ["spinach", "potato", "cauliflower", "tomato"], spices: ["garam masala", "turmeric", "cumin", "coriander"], herbs: ["cilantro", "curry leaves", "mint"], techniques: ["tandoor", "curry", "temper", "braise"] }),
  mexican: profile({ id: "mexican", name: "Mexican", aliases: ["mexico", "tex mex"], proteins: ["chicken", "beef", "shrimp", "beans"], grains: ["corn tortilla", "rice", "beans"], vegetables: ["tomato", "tomatillo", "poblano", "avocado"], spices: ["cumin", "chili", "chipotle"], herbs: ["cilantro", "epazote"], techniques: ["grill", "roast", "fry", "stew"] }),
  thai: profile({ id: "thai", name: "Thai", aliases: ["thailand"], proteins: ["chicken", "shrimp", "fish", "tofu"], grains: ["jasmine rice", "rice noodles"], vegetables: ["eggplant", "green beans", "bell pepper"], spices: ["chili", "galangal", "white pepper"], herbs: ["thai basil", "cilantro", "mint"], techniques: ["stir_fry", "curry", "grill", "steam"] }),
  chinese: profile({ id: "chinese", name: "Chinese", aliases: ["china", "sichuan", "cantonese"], proteins: ["chicken", "beef", "shrimp", "tofu"], grains: ["rice", "noodles"], vegetables: ["bok choy", "broccoli", "scallion", "bell pepper"], spices: ["five spice", "white pepper", "chili"], herbs: ["scallion", "cilantro"], techniques: ["stir_fry", "steam", "braise", "deep_fry"] }),
  japanese: profile({ id: "japanese", name: "Japanese", aliases: ["japan"], proteins: ["fish", "chicken", "beef", "tofu"], grains: ["short grain rice", "noodles"], vegetables: ["daikon", "scallion", "mushroom", "seaweed"], spices: ["shichimi", "white pepper"], herbs: ["shiso", "scallion"], techniques: ["grill", "simmer", "steam", "fry"] }),
  korean: profile({ id: "korean", name: "Korean", aliases: ["korea"], proteins: ["beef", "chicken", "pork", "tofu"], grains: ["rice", "noodles"], vegetables: ["cabbage", "scallion", "mushroom", "radish"], spices: ["gochugaru", "gochujang", "sesame"], herbs: ["scallion", "perilla"], techniques: ["grill", "stir_fry", "ferment", "braise"] }),
  french: profile({ id: "french", name: "French", aliases: ["france", "provencal"], proteins: ["chicken", "beef", "fish", "duck"], grains: ["potato", "bread", "rice"], vegetables: ["mushroom", "onion", "tomato", "leek"], spices: ["black pepper", "nutmeg", "mustard"], herbs: ["thyme", "tarragon", "parsley"], techniques: ["braise", "roast", "saute", "bake"] }),
  spanish: profile({ id: "spanish", name: "Spanish", aliases: ["spain", "iberian"], proteins: ["chicken", "fish", "shrimp", "beans"], grains: ["rice", "bread", "potato"], vegetables: ["tomato", "bell pepper", "potato", "artichoke"], spices: ["smoked paprika", "saffron", "black pepper"], herbs: ["parsley", "thyme"], techniques: ["paella", "stew", "grill", "roast"] }),
  moroccan: profile({ id: "moroccan", name: "Moroccan", aliases: ["morocco", "maghrebi"], proteins: ["chicken", "lamb", "fish", "chickpeas"], grains: ["couscous", "bread", "rice"], vegetables: ["tomato", "eggplant", "carrot", "zucchini"], spices: ["ras el hanout", "cumin", "cinnamon", "paprika"], herbs: ["cilantro", "parsley", "mint"], techniques: ["tagine", "stew", "grill", "bake"] })
});

export function getCuisineProfile(value: string) {
  const normalized = value.trim().toLowerCase().replace(/[^a-z]/g, "");
  return Object.values(CuisineProfiles).find((candidate) =>
    [candidate.id, candidate.name, ...candidate.aliases].some((alias) => alias.replace(/[^a-z]/gi, "").toLowerCase() === normalized)
  ) ?? null;
}
